// Generated by generate_portal.py. Do not edit manually.
window.PLAYOS_PORTAL = {
  "stats": {
    "sources": 31,
    "documents": 83,
    "knowledge": 13,
    "qa": 54,
    "topics": 19
  },
  "documents": [
    {
      "id": "DOC-077",
      "title": "Build do PlayOS Kernel 1",
      "area": "evidence",
      "status": "current",
      "priority": "P0",
      "description": "bzImage com mseal e NTSYNC; módulos globais e runtime pendentes",
      "href": "../patch-Linux7.1.8-Noble/results/BUILD_PLAYOS_KERNEL1_2026-08-19.md",
      "tags": "playos-kernel result current patch-Linux7.1.8-Noble/results/BUILD_PLAYOS_KERNEL1_2026-08-19.md"
    },
    {
      "id": "DOC-050",
      "title": "Build Generic de produção do PlayOS Noble 6.8.4",
      "area": "evidence",
      "status": "current",
      "priority": "P0",
      "description": "Build Generic completo com patches PlayOS",
      "href": "../patch-FreeBSD-Noble/results/BUILD_GENERIC_PROD_6.8.4_2026-08-18.md",
      "tags": "noble result current patch-FreeBSD-Noble/results/BUILD_GENERIC_PROD_6.8.4_2026-08-18.md"
    },
    {
      "id": "DOC-044",
      "title": "Build PlayOS Linux 7.1.8 com estudos FreeBSD",
      "area": "evidence",
      "status": "current",
      "priority": "P0",
      "description": "Build vanilla 7.1.8 com adaptações PlayOS",
      "href": "../patch-FreeBSD-Kernel-7.1.8/results/BUILD_PLAYOS_7.1.8_2026-08-18.md",
      "tags": "linux-7.1.8 result current patch-FreeBSD-Kernel-7.1.8/results/BUILD_PLAYOS_7.1.8_2026-08-18.md"
    },
    {
      "id": "DOC-081",
      "title": "Migração do perfil Ubuntu Noble para Linux 7.1.8",
      "area": "evidence",
      "status": "current",
      "priority": "P0",
      "description": "Forward-port do perfil Noble para uma base Linux 7.1.8 reproduzível",
      "href": "../patch-Noble-PlayOS-Kernel-7.1.8/ANALISE_MIGRACAO_NOBLE_PARA_7.1.8.md",
      "tags": "playos-kernel-718 audit current patch-Noble-PlayOS-Kernel-7.1.8/ANALISE_MIGRACAO_NOBLE_PARA_7.1.8.md"
    },
    {
      "id": "DOC-083",
      "title": "Relatório integral das diferenças em `Kernels/`",
      "area": "evidence",
      "status": "current",
      "priority": "P0",
      "description": "Auditoria integral e configuração dos overlays contra baselines externos",
      "href": "../Kernels/RELATORIO_DIFERENCAS_KERNELS_2026-08-22.md",
      "tags": "kernels audit current Kernels/RELATORIO_DIFERENCAS_KERNELS_2026-08-22.md"
    },
    {
      "id": "DOC-027",
      "title": "Resultados dos Estudos FreeBSD 15 `sys/kern` versus Ubuntu",
      "area": "evidence",
      "status": "current",
      "priority": "P0",
      "description": "Resultados de estudos e experimentos executados",
      "href": "../RESULTADOS_ESTUDOS_FREEBSD15_SYS_KERN_2026-08-18.md",
      "tags": "studies result current RESULTADOS_ESTUDOS_FREEBSD15_SYS_KERN_2026-08-18.md"
    },
    {
      "id": "DOC-074",
      "title": "Validação do backport NTSYNC",
      "area": "evidence",
      "status": "current",
      "priority": "P0",
      "description": "Backport NTSYNC compilado com BTF; runtime e boot pendentes",
      "href": "../patch-Linux7.1.8-Noble/results/VALIDACAO_NTSYNC_2026-08-19.md",
      "tags": "noble-linux718 result current patch-Linux7.1.8-Noble/results/VALIDACAO_NTSYNC_2026-08-19.md"
    },
    {
      "id": "DOC-045",
      "title": "Validação inicial — Linux vanilla 7.1.8",
      "area": "evidence",
      "status": "current",
      "priority": "P0",
      "description": "Não foi possível confirmar origem, tag ou commit da árvore local. Ela foi usada somente para análise e compatibilidade estática.",
      "href": "../patch-FreeBSD-Kernel-7.1.8/results/VALIDACAO_2026-08-18.md",
      "tags": "linux-7.1.8 result current patch-FreeBSD-Kernel-7.1.8/results/VALIDACAO_2026-08-18.md"
    },
    {
      "id": "DOC-022",
      "title": "Arquitetura do PlayOS: Linux e FreeBSD",
      "area": "freebsd",
      "status": "current",
      "priority": "P0",
      "description": "Arquitetura e fronteiras Linux/FreeBSD do PlayOS",
      "href": "../PLAYOS_ARQUITETURA_LINUX_FREEBSD_2026-08-18.md",
      "tags": "playos decision current PLAYOS_ARQUITETURA_LINUX_FREEBSD_2026-08-18.md"
    },
    {
      "id": "DOC-057",
      "title": "Inventário completo do FreeBSD 15.1-RELEASE-p2 presente no projeto",
      "area": "freebsd",
      "status": "current",
      "priority": "P0",
      "description": "Inventário completo da árvore FreeBSD",
      "href": "../patch-linux7.1.8-FreeBSD/INVENTARIO_FREEBSD_15.1_P2.md",
      "tags": "freebsd inventory current patch-linux7.1.8-FreeBSD/INVENTARIO_FREEBSD_15.1_P2.md"
    },
    {
      "id": "DOC-067",
      "title": "Referência de subsistemas FreeBSD para o PlayOS",
      "area": "freebsd",
      "status": "current",
      "priority": "P0",
      "description": "ID: KB-FBSD-SUBSYSTEMS",
      "href": "../supervised_learning/knowledge/freebsd/subsystem-reference.md",
      "tags": "freebsd reference current supervised_learning/knowledge/freebsd/subsystem-reference.md"
    },
    {
      "id": "DOC-024",
      "title": "Auditoria de Portabilidade — FreeBSD 15 `sys/kern` para Kernel Ubuntu Resolute",
      "area": "mapping",
      "status": "current",
      "priority": "P0",
      "description": "Auditoria por família de portabilidade sys/kern",
      "href": "../PORTABILIDADE_FREEBSD15_SYS_KERN_PARA_UBUNTU.md",
      "tags": "portability audit current PORTABILIDADE_FREEBSD15_SYS_KERN_PARA_UBUNTU.md"
    },
    {
      "id": "DOC-008",
      "title": "Integração de `sys/kern` do FreeBSD no Ubuntu",
      "area": "mapping",
      "status": "current",
      "priority": "P0",
      "description": "Decisão de integração em camadas",
      "href": "../INTEGRACAO_SYS_KERN_FREEBSD_NO_UBUNTU_2026-08-18.md",
      "tags": "portability decision current INTEGRACAO_SYS_KERN_FREEBSD_NO_UBUNTU_2026-08-18.md"
    },
    {
      "id": "DOC-061",
      "title": "Validação inicial — 18 de agosto de 2026",
      "area": "mapping",
      "status": "current",
      "priority": "P0",
      "description": "O host atual é Linux. Não estavam disponíveis bmake, config FreeBSD, mandoc, Kyua ou ATF para execução completa. Portanto não foram realizados:",
      "href": "../patch-linux7.1.8-FreeBSD/results/VALIDACAO_2026-08-18.md",
      "tags": "freebsd-reverse result current patch-linux7.1.8-FreeBSD/results/VALIDACAO_2026-08-18.md"
    },
    {
      "id": "DOC-005",
      "title": "Auditoria Completa de Arquitetura e Direção — Parcel Play OS",
      "area": "playos",
      "status": "current",
      "priority": "P0",
      "description": "Auditoria de direção e propostas",
      "href": "../AUDITORIA_COMPLETA_DIRECAO_2026-08-18.md",
      "tags": "project audit current AUDITORIA_COMPLETA_DIRECAO_2026-08-18.md"
    },
    {
      "id": "DOC-001",
      "title": "Auditoria das Alterações do Parcel Play OS — 18 de agosto de 2026",
      "area": "playos",
      "status": "current",
      "priority": "P0",
      "description": "Esta auditoria compara o workspace atual com o último commit existente:",
      "href": "../ANALISE_ALTERACOES_2026-08-18.md",
      "tags": "project audit current ANALISE_ALTERACOES_2026-08-18.md"
    },
    {
      "id": "DOC-071",
      "title": "Diretriz principal para Inteligências Artificiais — PlayOS",
      "area": "playos",
      "status": "current",
      "priority": "P0",
      "description": "Este é o arquivo de entrada obrigatório para qualquer IA, agente de código ou assistente que trabalhe neste projeto.",
      "href": "../AGENTS.md",
      "tags": "ai-governance instruction current AGENTS.md"
    },
    {
      "id": "DOC-069",
      "title": "Estado do portal HTML de documentação",
      "area": "playos",
      "status": "current",
      "priority": "P0",
      "description": "Estado e validação do portal documental gerado",
      "href": "../supervised_learning/HTML_PORTAL_STATUS.md",
      "tags": "documentation result current supervised_learning/HTML_PORTAL_STATUS.md"
    },
    {
      "id": "DOC-006",
      "title": "Comparação Inicial: OpenBSD e FreeBSD",
      "area": "bsd",
      "status": "current",
      "priority": "P1",
      "description": "Comparação extensa OpenBSD e FreeBSD",
      "href": "../COMPARACAO_OPENBSD_FREEBSD.md",
      "tags": "bsd-family comparison current COMPARACAO_OPENBSD_FREEBSD.md"
    },
    {
      "id": "DOC-068",
      "title": "Glossário BSD/Linux/PlayOS",
      "area": "bsd",
      "status": "current",
      "priority": "P1",
      "description": "ID: KB-BSD-GLOSSARY",
      "href": "../supervised_learning/knowledge/bsd-family/glossary.md",
      "tags": "bsd-family glossary current supervised_learning/knowledge/bsd-family/glossary.md"
    },
    {
      "id": "DOC-075",
      "title": "Backport NTSYNC do Linux 7.1.8 para Noble",
      "area": "evidence",
      "status": "current",
      "priority": "P1",
      "description": "ID: KB-LINUX-NTSYNC-NOBLE",
      "href": "../supervised_learning/knowledge/linux/ntsync-backport-noble.md",
      "tags": "noble-linux718 knowledge current supervised_learning/knowledge/linux/ntsync-backport-noble.md"
    },
    {
      "id": "DOC-063",
      "title": "Estudos FreeBSD `sys/kern` versus Linux/Ubuntu",
      "area": "evidence",
      "status": "current",
      "priority": "P1",
      "description": "Índice do kit de estudos reproduzíveis",
      "href": "../studies/freebsd15_sys_kern/README.md",
      "tags": "studies index current studies/freebsd15_sys_kern/README.md"
    },
    {
      "id": "DOC-047",
      "title": "FreeBSD 15.1 → Ubuntu Noble PlayOS Kernel",
      "area": "evidence",
      "status": "current",
      "priority": "P1",
      "description": "Patchset específico para criar o kernel playos-freebsd sobre Ubuntu Noble Linux 6.8. Este trabalho é separado do antigo alvo Ubuntu Resolute.",
      "href": "../patch-FreeBSD-Noble/README.md",
      "tags": "noble guide current patch-FreeBSD-Noble/README.md"
    },
    {
      "id": "DOC-010",
      "title": "Laboratório de DNA de Kernels: NitroCore",
      "area": "evidence",
      "status": "current",
      "priority": "P1",
      "description": "Este documento detalha a análise profunda dos fontes localizados na pasta Kernels/ e as ações para a criação do kernel NitroCore Híbrido.",
      "href": "../LABORATORIO_KERNELS.md",
      "tags": "kernels lab-guide current LABORATORIO_KERNELS.md"
    },
    {
      "id": "DOC-072",
      "title": "Linux 7.1.8 → PlayOS Kernel sobre Ubuntu Noble 6.8.4",
      "area": "evidence",
      "status": "current",
      "priority": "P1",
      "description": "Série de backports Linux nativos selecionados para enriquecer o kernel PlayOS Noble sem misturar subsistemas grandes ou ABI incompatível.",
      "href": "../patch-Linux7.1.8-Noble/README.md",
      "tags": "noble-linux718 guide current patch-Linux7.1.8-Noble/README.md"
    },
    {
      "id": "DOC-041",
      "title": "Manifesto",
      "area": "evidence",
      "status": "current",
      "priority": "P1",
      "description": "Manifesto do patchset Linux 7.1.8",
      "href": "../patch-FreeBSD-Kernel-7.1.8/MANIFEST.md",
      "tags": "linux-7.1.8 manifest current patch-FreeBSD-Kernel-7.1.8/MANIFEST.md"
    },
    {
      "id": "DOC-046",
      "title": "Manifesto de baseline",
      "area": "evidence",
      "status": "current",
      "priority": "P1",
      "description": "Manifesto do patchset Noble",
      "href": "../patch-FreeBSD-Noble/MANIFEST.md",
      "tags": "noble manifest current patch-FreeBSD-Noble/MANIFEST.md"
    },
    {
      "id": "DOC-073",
      "title": "Manifesto do backport Linux 7.1.8 para Noble",
      "area": "evidence",
      "status": "current",
      "priority": "P1",
      "description": "1. 0001-ntsync-backport-linux-7.1.8-to-noble-6.8.patch 2. 0002-mseal-and-playos-kernel-identity.patch",
      "href": "../patch-Linux7.1.8-Noble/MANIFEST.md",
      "tags": "noble-linux718 manifest current patch-Linux7.1.8-Noble/MANIFEST.md"
    },
    {
      "id": "DOC-080",
      "title": "Manifesto — PlayOS Kernel 7.1.8 com perfil Noble",
      "area": "evidence",
      "status": "current",
      "priority": "P1",
      "description": "1. identidade PlayOS Kernel 2; 2. documentação de estudo FreeBSD/Linux; 3. amostra inerte de bootconfig para initcalls; 4. selftests não destrutivos PlayOS/FreeBSD para sendfile, Landlock, cgroup v2,",
      "href": "../patch-Noble-PlayOS-Kernel-7.1.8/MANIFEST.md",
      "tags": "playos-kernel-718 manifest current patch-Noble-PlayOS-Kernel-7.1.8/MANIFEST.md"
    },
    {
      "id": "DOC-014",
      "title": "Matriz de Qualidade do Decágono (NitroCore)",
      "area": "evidence",
      "status": "current",
      "priority": "P1",
      "description": "Este documento detalha como o kernel NitroCore absorve e adapta as melhores qualidades técnicas dos 10 sistemas que compõem o nosso Decágono de Referência.",
      "href": "../MATRIZ_QUALIDADE.md",
      "tags": "quality matrix current MATRIZ_QUALIDADE.md"
    },
    {
      "id": "DOC-076",
      "title": "Migração Linux 7.1.8 para PlayOS Kernel",
      "area": "evidence",
      "status": "current",
      "priority": "P1",
      "description": "Data da auditoria: 2026-08-19",
      "href": "../patch-Linux7.1.8-Noble/MIGRACAO_LINUX_7.1.8_PARA_PLAYOS_KERNEL.md",
      "tags": "playos-kernel plan current patch-Linux7.1.8-Noble/MIGRACAO_LINUX_7.1.8_PARA_PLAYOS_KERNEL.md"
    },
    {
      "id": "DOC-079",
      "title": "Noble atualizado para PlayOS Kernel 7.1.8",
      "area": "evidence",
      "status": "current",
      "priority": "P1",
      "description": "Este patchset cria a linha principal do PlayOS Kernel sobre Linux vanilla 7.1.8. Ele reaproveita a política do Ubuntu Noble Generic, adapta a configuração às",
      "href": "../patch-Noble-PlayOS-Kernel-7.1.8/README.md",
      "tags": "playos-kernel-718 guide current patch-Noble-PlayOS-Kernel-7.1.8/README.md"
    },
    {
      "id": "DOC-042",
      "title": "Patchset FreeBSD → Linux vanilla 7.1.8",
      "area": "evidence",
      "status": "current",
      "priority": "P1",
      "description": "Área exclusiva para preparar patches inspirados no FreeBSD 15 sys/kern para o Linux upstream 7.1.8 usado pelo Parcel Play OS.",
      "href": "../patch-FreeBSD-Kernel-7.1.8/README.md",
      "tags": "linux-7.1.8 guide current patch-FreeBSD-Kernel-7.1.8/README.md"
    },
    {
      "id": "DOC-049",
      "title": "Primeiro build do kernel PlayOS FreeBSD Lab",
      "area": "evidence",
      "status": "superseded-by-generic",
      "priority": "P1",
      "description": "74134bfb6b720ca18a73931662cbcc8170ef1bed;",
      "href": "../patch-FreeBSD-Noble/results/BUILD_6.8.4_PLAYOS_FREEBSD_LAB1_2026-08-18.md",
      "tags": "noble result superseded-by-generic patch-FreeBSD-Noble/results/BUILD_6.8.4_PLAYOS_FREEBSD_LAB1_2026-08-18.md"
    },
    {
      "id": "DOC-043",
      "title": "Propostas condicionais",
      "area": "evidence",
      "status": "current",
      "priority": "P1",
      "description": "Usar os exemplos e selftests existentes em tools/testing/selftests/schedext. Uma futura política Parcel deve ser eBPF, sair com segurança para EEVDF e medir",
      "href": "../patch-FreeBSD-Kernel-7.1.8/proposals/README.md",
      "tags": "linux-7.1.8 proposal current patch-FreeBSD-Kernel-7.1.8/proposals/README.md"
    },
    {
      "id": "DOC-051",
      "title": "Resultados",
      "area": "evidence",
      "status": "current",
      "priority": "P1",
      "description": "O build mais completo é BUILDGENERICPROD6.8.42026-08-18.md. Ele usa a configuração amd64-generic extraída das annotations oficiais do Ubuntu e",
      "href": "../patch-FreeBSD-Noble/results/README.md",
      "tags": "noble index current patch-FreeBSD-Noble/results/README.md"
    },
    {
      "id": "DOC-048",
      "title": "Roadmap do kernel PlayOS Noble + FreeBSD",
      "area": "evidence",
      "status": "current",
      "priority": "P1",
      "description": "Resultado esperado: benefícios funcionais inspirados no FreeBSD sem patch de subsistema.",
      "href": "../patch-FreeBSD-Noble/ROADMAP.md",
      "tags": "noble plan current patch-FreeBSD-Noble/ROADMAP.md"
    },
    {
      "id": "DOC-032",
      "title": "Transparência e Catálogo de Fontes dos Kernels",
      "area": "evidence",
      "status": "current",
      "priority": "P1",
      "description": "Identidade e links de fontes de kernels",
      "href": "../TRANSPARENCIA_KERNEL.md",
      "tags": "kernels provenance current TRANSPARENCIA_KERNEL.md"
    },
    {
      "id": "DOC-036",
      "title": "Matriz de compatibilidade",
      "area": "freebsd",
      "status": "current",
      "priority": "P1",
      "description": "Matriz de roteamento de cargas",
      "href": "../freebsd-compatibility/COMPATIBILITY_MATRIX.md",
      "tags": "compatibility matrix current freebsd-compatibility/COMPATIBILITY_MATRIX.md"
    },
    {
      "id": "DOC-038",
      "title": "Parcel FreeBSD Compatibility Fabric",
      "area": "freebsd",
      "status": "current",
      "priority": "P1",
      "description": "Arquitetura de compatibilidade em camadas",
      "href": "../freebsd-compatibility/README.md",
      "tags": "compatibility architecture current freebsd-compatibility/README.md"
    },
    {
      "id": "DOC-037",
      "title": "Plano de implementação",
      "area": "freebsd",
      "status": "current",
      "priority": "P1",
      "description": "horas sem erro crítico.",
      "href": "../freebsd-compatibility/IMPLEMENTATION_PLAN.md",
      "tags": "compatibility plan current freebsd-compatibility/IMPLEMENTATION_PLAN.md"
    },
    {
      "id": "DOC-066",
      "title": "Roadmap de conhecimento BSD",
      "area": "freebsd",
      "status": "current",
      "priority": "P1",
      "description": "Criar entradas por família com símbolos, linhas, dependências, invariantes, locks, testes upstream, equivalente Linux e decisão PlayOS. Ordem:",
      "href": "../supervised_learning/ROADMAP_BSD_KNOWLEDGE.md",
      "tags": "freebsd roadmap current supervised_learning/ROADMAP_BSD_KNOWLEDGE.md"
    },
    {
      "id": "DOC-011",
      "title": "Verificação para um Live CD do FreeBSD",
      "area": "freebsd",
      "status": "current",
      "priority": "P1",
      "description": "Análise Live CD e instaladores",
      "href": "../LIVE_CD_FREEBSD.md",
      "tags": "freebsd-live analysis current LIVE_CD_FREEBSD.md"
    },
    {
      "id": "DOC-056",
      "title": "Análise Linux 7.1.8 → FreeBSD 15.1-p2",
      "area": "mapping",
      "status": "current",
      "priority": "P1",
      "description": "Análise invertida Linux para FreeBSD",
      "href": "../patch-linux7.1.8-FreeBSD/ANALISE_COMPARATIVA.md",
      "tags": "freebsd-reverse analysis current patch-linux7.1.8-FreeBSD/ANALISE_COMPARATIVA.md"
    },
    {
      "id": "DOC-058",
      "title": "Manifesto da tradução Linux 7.1.8 → FreeBSD 15.1-p2",
      "area": "mapping",
      "status": "current",
      "priority": "P1",
      "description": "Manifesto do patchset Linux para FreeBSD",
      "href": "../patch-linux7.1.8-FreeBSD/MANIFEST.md",
      "tags": "freebsd-reverse manifest current patch-linux7.1.8-FreeBSD/MANIFEST.md"
    },
    {
      "id": "DOC-059",
      "title": "Patchset Linux 7.1.8 → FreeBSD 15.1-p2",
      "area": "mapping",
      "status": "current",
      "priority": "P1",
      "description": "Este diretório prepara patches nativos para o FreeBSD inspirados em mecanismos do Linux 7.1.8. Nenhum código GPL do Linux é copiado para o FreeBSD.",
      "href": "../patch-linux7.1.8-FreeBSD/README.md",
      "tags": "freebsd-reverse guide current patch-linux7.1.8-FreeBSD/README.md"
    },
    {
      "id": "DOC-023",
      "title": "PlayOS unificado: Ubuntu Resolute + FreeBSD 15",
      "area": "mapping",
      "status": "current",
      "priority": "P1",
      "description": "Proposta de host Linux e FreeBSD Core virtualizado",
      "href": "../PLAYOS_UNIFICADO_UBUNTU_FREEBSD_2026-08-18.md",
      "tags": "playos architecture current PLAYOS_UNIFICADO_UBUNTU_FREEBSD_2026-08-18.md"
    },
    {
      "id": "DOC-060",
      "title": "Propostas ainda não implementadas",
      "area": "mapping",
      "status": "current",
      "priority": "P1",
      "description": "Estudar uma interface agregada de pressão de CPU, memória e I/O inspirada no Linux PSI. Antes de criar ABI, inventariar vm.stats, RACCT, scheduler stats,",
      "href": "../patch-linux7.1.8-FreeBSD/proposals/README.md",
      "tags": "freebsd-reverse proposal current patch-linux7.1.8-FreeBSD/proposals/README.md"
    },
    {
      "id": "DOC-003",
      "title": "Relatório de Aplicação dos Estudos FreeBSD 15 no Ubuntu Resolute",
      "area": "mapping",
      "status": "current",
      "priority": "P1",
      "description": "alteração foi aplicada ao kernel Ubuntu nesta etapa.",
      "href": "../APLICACAO_FREEBSD15_NO_UBUNTU_RESOLUTE_2026-08-18.md",
      "tags": "portability report current APLICACAO_FREEBSD15_NO_UBUNTU_RESOLUTE_2026-08-18.md"
    },
    {
      "id": "DOC-034",
      "title": "Verificação oficial do kernel Ubuntu Resolute",
      "area": "mapping",
      "status": "current",
      "priority": "P1",
      "description": "Correção de identidade Resolute versus Noble local",
      "href": "../VERIFICACAO_KERNEL_UBUNTU_RESOLUTE_2026-08-18.md",
      "tags": "ubuntu identity current VERIFICACAO_KERNEL_UBUNTU_RESOLUTE_2026-08-18.md"
    },
    {
      "id": "DOC-078",
      "title": "Migração para o PlayOS Kernel",
      "area": "playos",
      "status": "current",
      "priority": "P1",
      "description": "ID: KB-PLAYOS-KERNEL-MIGRATION",
      "href": "../supervised_learning/knowledge/linux/playos-kernel-migration.md",
      "tags": "playos-kernel knowledge current supervised_learning/knowledge/linux/playos-kernel-migration.md"
    },
    {
      "id": "DOC-082",
      "title": "PlayOS Kernel 7.1.8 com perfil Ubuntu Noble",
      "area": "playos",
      "status": "current",
      "priority": "P1",
      "description": "ID: KB-PLAYOS-KERNEL-718",
      "href": "../supervised_learning/knowledge/linux/playos-kernel-7.1.8.md",
      "tags": "playos-kernel-718 knowledge current supervised_learning/knowledge/linux/playos-kernel-7.1.8.md"
    },
    {
      "id": "DOC-070",
      "title": "Portal de documentação PlayOS",
      "area": "playos",
      "status": "current",
      "priority": "P1",
      "description": "Primeira versão do portal HTML que unifica a navegação da documentação BSD, Linux e PlayOS. Ele é estático, local e não foi publicado.",
      "href": "../documentation-portal/README.md",
      "tags": "documentation guide current documentation-portal/README.md"
    },
    {
      "id": "DOC-025",
      "title": "Registro de Progresso: Parcel Play OS",
      "area": "playos",
      "status": "current",
      "priority": "P1",
      "description": "Registro cronológico; não substitui fontes primárias",
      "href": "../PROGRESSO.md",
      "tags": "project log current PROGRESSO.md"
    },
    {
      "id": "DOC-009",
      "title": "A Tríade BSD: O Reforço de Elite do NitroCore",
      "area": "bsd",
      "status": "experimental",
      "priority": "P2",
      "description": "Proposta conceitual da tríade BSD",
      "href": "../INTEGRACAO_TRIADE_BSD.md",
      "tags": "bsd-family proposal experimental INTEGRACAO_TRIADE_BSD.md"
    },
    {
      "id": "DOC-039",
      "title": "Documentação do Kernel NitroCore",
      "area": "evidence",
      "status": "context",
      "priority": "P2",
      "description": "O NitroCore é o núcleo customizado do Parcel Play OS, projetado para oferecer performance em hardware moderno sem abandonar compatibilidade, segurança e confiabilidade. Durante o desenvolvimento, o kernel oficial do Ubun",
      "href": "../kernel.md",
      "tags": "kernels overview context kernel.md"
    },
    {
      "id": "DOC-012",
      "title": "Mídia Live híbrida com 11 opções de kernel/sistema",
      "area": "evidence",
      "status": "context",
      "priority": "P2",
      "description": "Construir uma única mídia Live cujo menu inicial ofereça oito kernels Linux e três sistemas BSD. Os oito kernels Linux poderão montar o rootfs Ubuntu compartilhado com GNOME, KDE Full e GDM. FreeBSD, NetBSD e OpenBSD rea",
      "href": "../LIVE_ISO_11_KERNELS.md",
      "tags": "live-media proposal context LIVE_ISO_11_KERNELS.md"
    },
    {
      "id": "DOC-018",
      "title": "A Trindade da Performance: Orbis OS, FreeBSD e SteamOS",
      "area": "freebsd",
      "status": "context",
      "priority": "P2",
      "description": "Este documento consolida a inteligência das três maiores referências mundiais em sistemas voltados para entretenimento e alta performance, servindo como a base técnica final para o Parcel Play OS.",
      "href": "../ORBIS_FREEBSD_STEAMOS.md",
      "tags": "gaming proposal context ORBIS_FREEBSD_STEAMOS.md"
    },
    {
      "id": "DOC-064",
      "title": "Análise Profunda: FreeBSD sys/kern (O Coração do Sistema)",
      "area": "freebsd",
      "status": "needs-migration",
      "priority": "P2",
      "description": "Este documento detalha a análise técnica dos arquivos em sys/kern do FreeBSD 15, focando em como portar essas tecnologias para o Parcel Play OS.",
      "href": "../supervised_learning/ANALISE_SYS_KERN_FREEBSD.md",
      "tags": "freebsd legacy-note needs-migration supervised_learning/ANALISE_SYS_KERN_FREEBSD.md"
    },
    {
      "id": "DOC-065",
      "title": "Aprendizagem Supervisionada: Núcleo FreeBSD (v15 & v16)",
      "area": "freebsd",
      "status": "needs-migration",
      "priority": "P2",
      "description": "Este documento registra o processo contínuo de análise e extração de inteligência do código-fonte do FreeBSD para benefício do Parcel Play OS.",
      "href": "../supervised_learning/APRENDIZAGEM_FREEBSD.md",
      "tags": "freebsd legacy-note needs-migration supervised_learning/APRENDIZAGEM_FREEBSD.md"
    },
    {
      "id": "DOC-016",
      "title": "Design de Interface: Central de Segurança Nitro",
      "area": "freebsd",
      "status": "experimental",
      "priority": "P2",
      "description": "A Central de Segurança Nitro é o painel de controle de integridade do Parcel Play OS, permitindo ao usuário monitorar e gerenciar o Decágono de Blindagem em tempo real.",
      "href": "../NITRO_SECURITY_DESIGN.md",
      "tags": "nitrocore design experimental NITRO_SECURITY_DESIGN.md"
    },
    {
      "id": "DOC-031",
      "title": "Estudo de Caso: Sony PlayStation & FreeBSD",
      "area": "freebsd",
      "status": "unverified-claims",
      "priority": "P2",
      "description": "Este documento explora a relação histórica e técnica entre a Sony Interactive Entertainment e o projeto FreeBSD, servindo como referência de sucesso para o Parcel Play OS.",
      "href": "../SONY_PLAYSTATION_FREEBSD.md",
      "tags": "gaming note unverified-claims SONY_PLAYSTATION_FREEBSD.md"
    },
    {
      "id": "DOC-015",
      "title": "Modo Jogo: Isolamento por Capacidades (Capsicum Style)",
      "area": "freebsd",
      "status": "experimental",
      "priority": "P2",
      "description": "O Modo Jogo do Parcel Play OS utiliza a filosofia Capsicum do FreeBSD para garantir que o processo do jogo tenha performance máxima com segurança absoluta, eliminando o overhead dos sandboxes tradicionais.",
      "href": "../MODO_JOGO_CAPSICUM.md",
      "tags": "security proposal experimental MODO_JOGO_CAPSICUM.md"
    },
    {
      "id": "DOC-019",
      "title": "Orquestração de Elite: Orbis OS, FreeBSD e SteamOS",
      "area": "freebsd",
      "status": "context",
      "priority": "P2",
      "description": "Este documento detalha como o Parcel Play OS absorve a inteligência das três plataformas de entretenimento mais poderosas do mundo, focando em isolamento de segurança e performance de vanguarda.",
      "href": "../ORBIS_FREEBSD_STEAMOS_INTEGRATION.md",
      "tags": "gaming proposal context ORBIS_FREEBSD_STEAMOS_INTEGRATION.md"
    },
    {
      "id": "DOC-062",
      "title": "Resumo da Instalação do KDE no FreeBSD",
      "area": "freebsd",
      "status": "context",
      "priority": "P2",
      "description": "Este documento resume as soluções e comandos discutidos no chat para instalar o ambiente gráfico KDE Plasma no FreeBSD e resolver problemas de privilégios de acesso.",
      "href": "../resumo_instalacao_kde_freebsd.md",
      "tags": "freebsd-desktop note context resumo_instalacao_kde_freebsd.md"
    },
    {
      "id": "DOC-035",
      "title": "ZFS Gaming Zone: O Sistema de Arquivos do NitroCore",
      "area": "freebsd",
      "status": "experimental",
      "priority": "P2",
      "description": "O Parcel Play OS integra a tecnologia ZFS (vinda do FreeBSD e Oracle) para criar a \"Gaming Zone\", uma partição inteligente e ultra-rápida projetada para o carregamento imediato de jogos modernos (UE5, 4K/8K Textures).",
      "href": "../ZFS_GAMING_ZONE.md",
      "tags": "storage proposal experimental ZFS_GAMING_ZONE.md"
    },
    {
      "id": "DOC-055",
      "title": "Aplicação inicial do estudo `sys/kern` no kernel Ubuntu local",
      "area": "mapping",
      "status": "historical",
      "priority": "P2",
      "description": "A árvore declara Linux 6.8.4 e pacote Ubuntu Noble 6.8.0-30.30. Ela não é o Ubuntu Resolute Linux 7.0 oficial. A aplicação inicia o laboratório e não deve",
      "href": "../patch-FreeBSD-Ubuntu/results/APLICACAO_INICIAL_6.8_2026-08-18.md",
      "tags": "ubuntu result historical patch-FreeBSD-Ubuntu/results/APLICACAO_INICIAL_6.8_2026-08-18.md"
    },
    {
      "id": "DOC-052",
      "title": "Manifesto do patchset",
      "area": "mapping",
      "status": "historical",
      "priority": "P2",
      "description": "Adiciona ao kernel a especificação da tradução conceitual. Não altera ABI, configuração ou comportamento.",
      "href": "../patch-FreeBSD-Ubuntu/MANIFEST.md",
      "tags": "ubuntu manifest historical patch-FreeBSD-Ubuntu/MANIFEST.md"
    },
    {
      "id": "DOC-033",
      "title": "O Quarteto de Elite: A Fundação do Parcel Play OS",
      "area": "mapping",
      "status": "context",
      "priority": "P2",
      "description": "Este documento detalha como o Parcel Play OS unifica as quatro maiores potências tecnológicas do mundo Unix e Linux para criar o sistema operacional definitivo de entretenimento e produtividade.",
      "href": "../UBUNTU_FREEBSD_ORBIS_STEAMOS.md",
      "tags": "gaming proposal context UBUNTU_FREEBSD_ORBIS_STEAMOS.md"
    },
    {
      "id": "DOC-053",
      "title": "Patchset FreeBSD → Ubuntu Resolute",
      "area": "mapping",
      "status": "historical",
      "priority": "P2",
      "description": "Este diretório é a área exclusiva de preparação dos patches inspirados no Kernels/FreeBSD 15/sys/kern para o kernel Ubuntu Resolute do Parcel Play OS.",
      "href": "../patch-FreeBSD-Ubuntu/README.md",
      "tags": "ubuntu guide historical patch-FreeBSD-Ubuntu/README.md"
    },
    {
      "id": "DOC-054",
      "title": "Propostas ainda não convertidas em patches",
      "area": "mapping",
      "status": "historical",
      "priority": "P2",
      "description": "Implementar primeiro como política schedext quando presente no baseline. Exigir fallback automático e benchmarks de frame time, throughput, PSI, energia e starvation. Não copiar schedule.c.",
      "href": "../patch-FreeBSD-Ubuntu/proposals/README.md",
      "tags": "ubuntu proposal historical patch-FreeBSD-Ubuntu/proposals/README.md"
    },
    {
      "id": "DOC-002",
      "title": "Análise do Projeto Parcel Play OS",
      "area": "playos",
      "status": "historical",
      "priority": "P2",
      "description": "de boot, documentação e artefatos locais do diretório Parcel Play OS.",
      "href": "../ANALISE_PROJETO_2026-08-15.md",
      "tags": "project audit historical ANALISE_PROJETO_2026-08-15.md"
    },
    {
      "id": "DOC-004",
      "title": "Arquitetura de Boot: Menu Híbrido com 11 Opções",
      "area": "playos",
      "status": "context",
      "priority": "P2",
      "description": "Este documento detalha o funcionamento do processo de boot do Parcel Play OS, desde a inicialização do Live CD até a transição para o sistema instalado.",
      "href": "../ARQUITETURA_BOOT.md",
      "tags": "boot design context ARQUITETURA_BOOT.md"
    },
    {
      "id": "DOC-017",
      "title": "Design de Interface: Nitro-Switcher Widget",
      "area": "playos",
      "status": "experimental",
      "priority": "P2",
      "description": "O Nitro-Switcher é um widget de alta performance para o painel do KDE Plasma 6 que permite ao usuário gerenciar e alternar entre os 10 sabores do kernel NitroCore sem precisar entrar em menus complexos.",
      "href": "../NITRO_SWITCHER_DESIGN.md",
      "tags": "nitrocore design experimental NITRO_SWITCHER_DESIGN.md"
    },
    {
      "id": "DOC-030",
      "title": "Estratégia de Auto-Cura (Self-Healing): Nitro-FMA",
      "area": "playos",
      "status": "context",
      "priority": "P2",
      "description": "O Parcel Play OS integra uma camada de resiliência inspirada no Solaris FMA (Fault Management Architecture) e no openSUSE OpenQA, garantindo que o sistema seja capaz de diagnosticar e corrigir falhas sem intervenção huma",
      "href": "../SELF_HEALING_STRATEGY.md",
      "tags": "reliability design context SELF_HEALING_STRATEGY.md"
    },
    {
      "id": "DOC-007",
      "title": "Instalador mínimo do Parcel Play OS",
      "area": "playos",
      "status": "context",
      "priority": "P2",
      "description": "Entregar uma Live ISO Resolute amd64 que:",
      "href": "../INSTALADOR.md",
      "tags": "installer design context INSTALADOR.md"
    },
    {
      "id": "DOC-013",
      "title": "macOS: A Maestria Híbrida (Mach + FreeBSD)",
      "area": "playos",
      "status": "context",
      "priority": "P2",
      "description": "O macOS (baseado no núcleo Darwin/XNU) serve como a referência máxima para o Parcel Play OS no que diz respeito à arquitetura híbrida e à integração vertical entre hardware (Apple Silicon) e software.",
      "href": "../MACOS_TECH.md",
      "tags": "other-os note context MACOS_TECH.md"
    },
    {
      "id": "DOC-040",
      "title": "NitroCore: O Contêiner de Performance do Parcel Play OS",
      "area": "playos",
      "status": "experimental",
      "priority": "P2",
      "description": "A pasta nitrocore/ é o coração das otimizações proprietárias do nosso kernel, seguindo o modelo arquitetural da pasta ubuntu/ encontrada no kernel da Canonical.",
      "href": "../nitrocore/nitrocore.md",
      "tags": "nitrocore overview experimental nitrocore/nitrocore.md"
    },
    {
      "id": "DOC-020",
      "title": "Orbis OS: A Engenharia por trás do PlayStation (PS4/PS5)",
      "area": "playos",
      "status": "context",
      "priority": "P2",
      "description": "O Orbis OS é o sistema operacional proprietário da Sony Interactive Entertainment. Ele serve como a referência máxima de como um núcleo FreeBSD pode ser transformado em uma plataforma de entretenimento de alta performanc",
      "href": "../ORBIS_OS.md",
      "tags": "gaming note context ORBIS_OS.md"
    },
    {
      "id": "DOC-021",
      "title": "Plano Estratégico: Parcel Play OS",
      "area": "playos",
      "status": "context",
      "priority": "P2",
      "description": "Este documento consolida a estratégia de desenvolvimento do Parcel Play OS, integrando a robustez do Ubuntu 26 com a tecnologia de performance do Thunder SDK, mantendo compatibilidade total.",
      "href": "../PLAN_ESTRATEGICO.md",
      "tags": "project plan context PLAN_ESTRATEGICO.md"
    },
    {
      "id": "DOC-026",
      "title": "Ranking de Influência e Enquadramento Arquitetural",
      "area": "playos",
      "status": "context",
      "priority": "P2",
      "description": "Este documento classifica os sistemas operacionais de referência baseando-se no nível de integração técnica e influência que eles exercem sobre a arquitetura final do Parcel Play OS.",
      "href": "../RANKING_ARQUITETURA.md",
      "tags": "project ranking context RANKING_ARQUITETURA.md"
    },
    {
      "id": "DOC-029",
      "title": "Resumo das Interações: Projeto Parcel Play OS",
      "area": "playos",
      "status": "historical",
      "priority": "P2",
      "description": "Este documento resume as discussões e decisões tomadas durante as sessões de desenvolvimento até o momento.",
      "href": "../RESUMO_DO_CHAT.md",
      "tags": "project summary historical RESUMO_DO_CHAT.md"
    },
    {
      "id": "DOC-028",
      "title": "Resumo do trabalho realizado em 18 de agosto de 2026",
      "area": "playos",
      "status": "historical",
      "priority": "P2",
      "description": "O trabalho de hoje transformou a pesquisa FreeBSD/Linux do Parcel Play OS em uma base técnica rastreável. Foram auditadas árvores de kernel, executados cinco",
      "href": "../RESUMO_DIA_2026-08-18.md",
      "tags": "project summary historical RESUMO_DIA_2026-08-18.md"
    }
  ]
};
