#!/usr/bin/env python3
"""Generate the static portal catalog from supervised_learning metadata."""

from __future__ import annotations

import csv
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "supervised_learning"
PORTAL = ROOT / "documentation-portal"


def read_tsv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as stream:
        return list(csv.DictReader(stream, delimiter="\t"))


def first_heading(text: str, fallback: str) -> str:
    match = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    return match.group(1).strip() if match else fallback


def first_paragraph(text: str) -> str:
    lines: list[str] = []
    in_fence = False
    for raw in text.splitlines():
        line = raw.strip()
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence or not line or line.startswith(("#", ">", "-", "*", "|")):
            if lines:
                break
            continue
        lines.append(line)
        if len(" ".join(lines)) >= 150:
            break
    paragraph = re.sub(r"[`*_]", "", " ".join(lines))
    return paragraph[:220].rstrip() or "Documento técnico catalogado do projeto PlayOS."


def category(area: str, path: str) -> str:
    value = f"{area} {path}".lower()
    if any(term in value for term in ("noble", "linux-7.1.8", "studies", "quality", "kernels")):
        return "evidence"
    if any(term in value for term in ("portability", "freebsd-reverse", "ubuntu")):
        return "mapping"
    if any(term in value for term in ("bsd-family", "openbsd", "netbsd")):
        return "bsd"
    if any(term in value for term in ("freebsd", "compatibility", "storage", "security")):
        return "freebsd"
    return "playos"


def priority(role: str, status: str) -> str:
    if role in {"decision", "audit", "inventory", "result", "reference", "instruction"} and status == "current":
        return "P0"
    if status in {"current", "superseded-by-generic"}:
        return "P1"
    return "P2"


def count_jsonl(path: Path) -> int:
    return sum(1 for line in path.read_text(encoding="utf-8").splitlines() if line.strip())


def main() -> None:
    inventory = read_tsv(BASE / "catalog/document_inventory.tsv")
    sources = read_tsv(BASE / "catalog/sources.tsv")
    topics = read_tsv(BASE / "catalog/topics.tsv")
    source_by_path = {row["path"]: row for row in sources}
    documents: list[dict[str, str]] = []
    for row in inventory:
        relative = row["path"]
        path = ROOT / relative
        text = path.read_text(encoding="utf-8")
        source = source_by_path.get(relative)
        documents.append({
            "id": row["document_id"],
            "title": first_heading(text, path.stem.replace("_", " ").title()),
            "area": category(row["area"], relative),
            "status": row["status"],
            "priority": priority(row["role"], row["status"]),
            "description": source["description"] if source else first_paragraph(text),
            "href": f"../{relative}",
            "tags": f"{row['area']} {row['role']} {row['status']} {relative}",
        })
    documents.sort(key=lambda item: (item["priority"], item["area"], item["title"].casefold()))
    qa_total = sum(count_jsonl(path) for path in (BASE / "datasets").glob("*.jsonl"))
    qa_total += sum(count_jsonl(path) for path in (BASE / "evaluations").glob("*.jsonl"))
    stats = {
        "sources": len(sources),
        "documents": len(inventory),
        "knowledge": len(list((BASE / "knowledge").rglob("*.md"))),
        "qa": qa_total,
        "topics": len(topics),
    }
    payload = "// Generated by generate_portal.py. Do not edit manually.\n"
    payload += "window.PLAYOS_PORTAL = " + json.dumps(
        {"stats": stats, "documents": documents}, ensure_ascii=False, indent=2
    ) + ";\n"
    (PORTAL / "generated-data.js").write_text(payload, encoding="utf-8")
    print(f"Generated {len(documents)} portal documents from catalog; stats={stats}")


if __name__ == "__main__":
    main()
