Dir::ArchiveDir ".";
TreeDefault::Directory ".";
TreeDefault::SrcDirectory ".";
Default::Packages::Extensions ".deb";
Default::Packages::Compress ". gzip";

BinDirectory "pool/main" {
    Packages "dists/trixie/main/binary-amd64/Packages";
    BinOverride "";
    ExtraOverride "";
};
