#
# Makefile for NitroCore submodules
#

obj-$(CONFIG_NITRO_SCHED)    += sched/nitro_sched.o
obj-$(CONFIG_NITRO_OMNILOCK) += mm/omnilock.o
obj-$(CONFIG_NITRO_HARDENED) += security/nitro_hardened.o
obj-$(CONFIG_NITRO_NET_XDP)  += net/nitro_net.o
