#
# Makefile for NitroCore submodules
#

obj-$(CONFIG_NITRO_SCHED)    += sched/nitro_sched.o
obj-$(CONFIG_NITRO_OMNILOCK) += mm/omnilock.o
obj-$(CONFIG_NITRO_HARDENED) += security/nitro_hardened.o
obj-$(CONFIG_NITRO_JAIL)     += security/nitro_jail.o
obj-$(CONFIG_NITRO_CFI)      += security/nitro_cfi.o
obj-$(CONFIG_NITRO_NTSYNC)   += sync/nitro_ntsync.o
obj-$(CONFIG_NITRO_AUDIO)    += audio/nitro_audio.o
obj-$(CONFIG_NITRO_STORAGE)  += storage/nitro_storage.o
obj-$(CONFIG_NITRO_NET_XDP)  += net/nitro_net.o
obj-$(CONFIG_NITROCORE)      += fs/nitro_prefetcher.o
