# ==============================================================================
# Configuração do Sistema e Init (systemd) — Angel OS
# ==============================================================================

HOSTNAME="angelos"
LOCALE="pt_BR.UTF-8"
TIMEZONE="America/Sao_Paulo"
DEFAULT_TARGET="graphical.target"
ENABLE_SERVICES=("systemd-udevd" "NetworkManager" "pipewire" "bluetooth" "sddm")
