# ==============================================================================
# Configuração da ISO Live — Angel OS Build System
# ==============================================================================

ISO_NAME="Angel-OS-KDE-Full"
ISO_VERSION="1.0.0-alpha"
ISO_LABEL="ANGEL_OS_KDE"
OUTPUT_DIR="output"
SQUASHFS_COMPRESSION="xz"
BOOTLOADER="grub2-efi"
