#!/bin/sh
set -eu

lb config noauto \
  --mode debian \
  --architectures amd64 \
  --distribution trixie \
  --archive-areas "main contrib non-free-firmware" \
  --mirror-bootstrap https://deb.debian.org/debian/ \
  --mirror-chroot https://deb.debian.org/debian/ \
  --mirror-binary https://deb.debian.org/debian/ \
  --mirror-security https://security.debian.org/debian-security/ \
  --parent-mirror-bootstrap https://deb.debian.org/debian/ \
  --parent-mirror-chroot https://deb.debian.org/debian/ \
  --parent-mirror-binary https://deb.debian.org/debian/ \
  --parent-mirror-security https://security.debian.org/debian-security/ \
  --security true \
  --updates true \
  --binary-images iso-hybrid \
  --bootloaders "grub-pc grub-efi" \
  --debian-installer none \
  --initramfs live-boot \
  --initsystem systemd \
  --linux-packages none \
  --apt-recommends true \
  --memtest none \
  --iso-application "PlayOS Debian KDE Full Vanilla 7.3" \
  --iso-publisher "PlayOS Project" \
  --iso-volume "PLAYOS_D13_KDE_V73" \
  --bootappend-live "boot=live components username=playos hostname=playos locales=pt_BR.UTF-8 keyboard-layouts=br" \
  "${@}"
