---
defaultGroups:
  - adm
  - cdrom
  - dip
  - lpadmin
  - plugdev
  - sudo
  - users
autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: false
doReusePassword: false
passwordRequirements:
  minLength: 8
  maxLength: 0
  libpwquality:
    - minlen=8
