---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false
requirements:
  requiredStorage: 8
  requiredRam: 1.5
  internetCheckUrl: ""
  check:
    - storage
    - ram
    - root
