---
efi:
  mountPoint: /boot/efi
  recommendedSize: 512MiB
  minimumSize: 300MiB
  label: EFI
userSwapChoices: [ none, small, file ]
initialPartitioningChoice: none
initialSwapChoice: none
defaultFileSystemType: ext4
requiredStorage: 8
