# ==============================================================================
# Configuração do Sistema Angel OS (Debian Trixie + Kernel 7.3 + KDE-Full)
# ==============================================================================

OS_NAME="Angel OS"
OS_SLOGAN="The Linux unix-like"
OS_VERSION="1.0.0-alpha"
OS_CODENAME="Seraphin"
OS_FLAVOR="KDE-Full"

# Kernel Target
TARGET_KERNEL_NAME="Seraphin Linux"
TARGET_KERNEL_VERSION="7.3.0-vanilla"

# Userspace & Base Distro
DEFAULT_BASE_DISTRO="debian-trixie"
PACKAGE_MANAGER="apt"
DEFAULT_DESKTOP="KDE Plasma Full"
DEFAULT_DISPLAY_MANAGER="SDDM"
DEFAULT_COMPOSITOR="KWin / Wayland"
