package com.projectwizard

import android.os.Bundle
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.animation.*
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.automirrored.filled.ArrowForward
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.text.input.TransformedText
import androidx.compose.ui.text.input.OffsetMapping
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.window.Dialog
import com.projectwizard.model.ProjectTemplate
import com.projectwizard.model.GeneratedProject
import com.projectwizard.model.WorkspaceManager
import com.projectwizard.model.ALL_TEMPLATES
import com.projectwizard.theme.getActiveColorScheme
import com.projectwizard.theme.ThemeManager
import com.projectwizard.theme.ThemeType
import com.projectwizard.view.SyntaxHighlighter
import com.projectwizard.service.PersistenceService
import com.projectwizard.service.GitService
import java.io.File
import java.util.ArrayList
import java.util.Locale

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()

        // Seed some starter projects on first launch
        WorkspaceManager.seedSampleProjects(this)

        setContent {
            val colorScheme = getActiveColorScheme()
            MaterialTheme(colorScheme = colorScheme) {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    AppShell()
                }
            }
        }
    }
}

// Global active navigation target state
enum class Screen {
    HOME,
    NEW_PROJECT,
    OPEN_PROJECT,
    TEMPLATES,
    GIT,
    GITHUB,
    SETTINGS,
    ABOUT,
    WORKSPACE
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AppShell() {
    val context = LocalContext.current
    val persistenceService = remember { PersistenceService(context) }
    var currentScreen by remember { mutableStateOf(Screen.HOME) }
    var selectedProject by remember { mutableStateOf<GeneratedProject?>(null) }
    var selectedTemplateForWizard by remember { mutableStateOf<ProjectTemplate?>(null) }

    // Dynamic state of loaded projects in the workspace
    var projectList by remember { mutableStateOf(WorkspaceManager.listProjects(context)) }

    // Restore last opened project
    LaunchedEffect(Unit) {
        val savedTheme = persistenceService.theme
        if (savedTheme != null) {
            try {
                ThemeManager.currentTheme = ThemeType.valueOf(savedTheme)
            } catch (e: Exception) {}
        }

        val lastPath = persistenceService.lastProjectPath as? String
        if (lastPath != null) {
            val file = File(lastPath)
            if (file.exists() && file.isDirectory) {
                val projects: List<GeneratedProject> = WorkspaceManager.listProjects(context)
                var found: GeneratedProject? = null
                for (proj in projects) {
                    if (proj.path == file.absolutePath) {
                        found = proj
                        break
                    }
                }
                if (found != null) {
                    selectedProject = found
                    currentScreen = Screen.WORKSPACE
                }
            }
        }
    }

    // Edge-to-edge window insets padding
    val windowInsets = WindowInsets.systemBars

    // Sidebar navigation action helper
    val navigateTo: (Screen) -> Unit = { target ->
        currentScreen = target
    }

    // Callback when a project is generated by the Wizard
    val onProjectCreated: (String, String, String, String, String) -> Unit = { name, group, artifact, lang, build ->
        val dir = WorkspaceManager.createProject(context, name, group, artifact, lang, build)
        projectList = WorkspaceManager.listProjects(context)
        selectedProject = GeneratedProject(
            name = dir.name,
            path = dir.absolutePath,
            language = lang,
            buildTool = build,
            group = group
        )
        persistenceService.saveLastProjectPath(dir.absolutePath)
        currentScreen = Screen.WORKSPACE
        Toast.makeText(context, "Project '$name' created!", Toast.LENGTH_SHORT).show()
    }

    BoxWithConstraints(
        modifier = Modifier
            .fillMaxSize()
            .windowInsetsPadding(windowInsets)
    ) {
        val isWide = this.maxWidth > 720.dp

        Row(modifier = Modifier.fillMaxSize()) {
            // Left sidebar for Expanded screens, or simple icon-rail
            if (isWide) {
                SidebarRail(
                    currentScreen = currentScreen,
                    onNavigate = { target: Screen ->
                        navigateTo(target)
                    },
                    modifier = Modifier
                        .width(240.dp)
                        .fillMaxHeight()
                        .background(MaterialTheme.colorScheme.surface)
                        .border(1.dp, MaterialTheme.colorScheme.outline, RoundedCornerShape(0.dp))
                )
            }

                // Main application column (Title Bar, Body Workspace, Status Bar)
                Column(modifier = Modifier.weight(1f)) {
                    // Top Action Menu Bar
                TopMenuBar(
                    currentScreen = currentScreen,
                    onNavigate = navigateTo,
                    onExit = { /* Simulated Exit */ }
                )

                HorizontalDivider(color = MaterialTheme.colorScheme.outline, thickness = 1.dp)

                // Main body area (Workspace)
                Box(
                    modifier = Modifier
                        .weight(1f)
                        .fillMaxWidth()
                ) {
                    when (currentScreen) {
                        Screen.HOME -> DashboardScreen(
                            onNewProject = {
                                selectedTemplateForWizard = null
                                navigateTo(Screen.NEW_PROJECT)
                            },
                            onOpenProject = {
                                navigateTo(Screen.OPEN_PROJECT)
                            }
                        )
                        Screen.NEW_PROJECT -> NewProjectWizardScreen(
                            initialTemplate = selectedTemplateForWizard,
                            onCancel = { navigateTo(Screen.HOME) },
                            onFinish = onProjectCreated
                        )
                        Screen.OPEN_PROJECT -> OpenProjectScreen(
                            projects = projectList,
                            onProjectSelected = { proj ->
                                selectedProject = proj
                                persistenceService.saveLastProjectPath(proj.path)
                                navigateTo(Screen.WORKSPACE)
                            },
                            onDeleteProject = { proj ->
                                val dir = File(proj.path)
                                if (dir.exists()) {
                                    dir.deleteRecursively()
                                }
                                projectList = WorkspaceManager.listProjects(context)
                                Toast.makeText(context, "Deleted project ${proj.name}", Toast.LENGTH_SHORT).show()
                            }
                        )
                        Screen.TEMPLATES -> TemplatesScreen(
                            onSelectTemplate = { temp ->
                                selectedTemplateForWizard = temp
                                navigateTo(Screen.NEW_PROJECT)
                            }
                        )
                        Screen.GIT -> GitScreen(selectedProject)
                        Screen.GITHUB -> GitHubScreen()
                        Screen.SETTINGS -> SettingsScreen(persistenceService)
                        Screen.ABOUT -> AboutScreen()
                        Screen.WORKSPACE -> {
                            val activeProj = selectedProject
                            if (activeProj != null) {
                                ProjectWorkspaceScreen(
                                    project = activeProj,
                                    persistenceService = persistenceService,
                                    onCloseWorkspace = {
                                        selectedProject = null
                                        persistenceService.saveLastProjectPath("")
                                        navigateTo(Screen.OPEN_PROJECT)
                                    }
                                )
                            } else {
                                navigateTo(Screen.OPEN_PROJECT)
                            }
                        }
                    }
                }

                HorizontalDivider(color = MaterialTheme.colorScheme.outline, thickness = 1.dp)

                // IDE Bottom Status bar
                BottomStatusBar(
                    currentScreen = currentScreen,
                    activeProject = selectedProject
                )
            }
        }

        // Bottom Navigation Bar for narrow screens (portrait phones)
        if (!isWide) {
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .align(Alignment.BottomCenter)
                    .background(MaterialTheme.colorScheme.surface)
            ) {
                // Since edge-to-edge system navigation might collide, we render a highly compact navigation row
                // overlay only if absolutely needed, but standard practice is a elegant bottom bar.
                // Let's implement it inside the layout rather than overlay to avoid covering content.
            }
        }
    }
}

// Side Navigation Rail / Sidebar Drawer for Wide screens
@Composable
fun SidebarRail(
    currentScreen: Screen,
    onNavigate: (Screen) -> Unit,
    modifier: Modifier = Modifier
) {
    Column(
        modifier = modifier.padding(12.dp),
        verticalArrangement = Arrangement.SpaceBetween
    ) {
        Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
            // App Header Branding
            Row(
                verticalAlignment = Alignment.CenterVertically,
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(vertical = 12.dp, horizontal = 8.dp)
            ) {
                Text(
                    text = "🧙‍♂️ Project Wizard",
                    fontSize = 18.sp,
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.primary
                )
            }

            Spacer(modifier = Modifier.height(10.dp))

            SidebarButton("🏠 Home", Screen.HOME, currentScreen, onNavigate)
            SidebarButton("📦 New Project", Screen.NEW_PROJECT, currentScreen, onNavigate)
            SidebarButton("📂 Open Project", Screen.OPEN_PROJECT, currentScreen, onNavigate)
            SidebarButton("📁 Templates", Screen.TEMPLATES, currentScreen, onNavigate)

            HorizontalDivider(color = MaterialTheme.colorScheme.outline, modifier = Modifier.padding(vertical = 8.dp))

            SidebarButton("🌿 Git", Screen.GIT, currentScreen, onNavigate)
            SidebarButton("☁ GitHub", Screen.GITHUB, currentScreen, onNavigate)

            HorizontalDivider(color = MaterialTheme.colorScheme.outline, modifier = Modifier.padding(vertical = 8.dp))

            SidebarButton("⚙ Settings", Screen.SETTINGS, currentScreen, onNavigate)
            SidebarButton("ℹ About", Screen.ABOUT, currentScreen, onNavigate)
        }

        // Footer version info
        Text(
            text = "Version 1.0.0 (Beta)",
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
            modifier = Modifier
                .align(Alignment.CenterHorizontally)
                .padding(bottom = 8.dp)
        )
    }
}

@Composable
fun SidebarButton(
    label: String,
    target: Screen,
    active: Screen,
    onNavigate: (Screen) -> Unit
) {
    val isSelected = active == target || (target == Screen.OPEN_PROJECT && active == Screen.WORKSPACE)
    val buttonColors = if (isSelected) {
        ButtonDefaults.buttonColors(
            containerColor = MaterialTheme.colorScheme.primary,
            contentColor = MaterialTheme.colorScheme.onPrimary
        )
    } else {
        ButtonDefaults.buttonColors(
            containerColor = Color.Transparent,
            contentColor = MaterialTheme.colorScheme.onSurface
        )
    }

    Button(
        onClick = { onNavigate(target) },
        colors = buttonColors,
        shape = RoundedCornerShape(8.dp),
        contentPadding = PaddingValues(horizontal = 14.dp, vertical = 10.dp),
        modifier = Modifier
            .fillMaxWidth()
            .testTag("nav_btn_" + target.name.lowercase(Locale.ROOT)),
        elevation = null
    ) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.Start,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Text(
                text = label,
                fontSize = 14.sp,
                fontWeight = if (isSelected) FontWeight.SemiBold else FontWeight.Normal
            )
        }
    }
}

// Top Menu bar supporting File, Help and dynamic quick actions
@Composable
fun TopMenuBar(
    currentScreen: Screen,
    onNavigate: (Screen) -> Unit,
    onExit: () -> Unit
) {
    var showFileMenu by remember { mutableStateOf(false) }
    var showHelpMenu by remember { mutableStateOf(false) }

    Row(
        modifier = Modifier
            .fillMaxWidth()
            .background(MaterialTheme.colorScheme.surfaceVariant)
            .padding(horizontal = 12.dp, vertical = 6.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween
    ) {
        // Desktop style menu buttons
        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
            Box {
                TextButton(onClick = { showFileMenu = true }) {
                    Text("File", color = MaterialTheme.colorScheme.onSurfaceVariant)
                }
                DropdownMenu(
                    expanded = showFileMenu,
                    onDismissRequest = { showFileMenu = false }
                ) {
                    DropdownMenuItem(
                        text = { Text("🏠 Home") },
                        onClick = {
                            onNavigate(Screen.HOME)
                            showFileMenu = false
                        }
                    )
                    DropdownMenuItem(
                        text = { Text("📦 New Project...") },
                        onClick = {
                            onNavigate(Screen.NEW_PROJECT)
                            showFileMenu = false
                        }
                    )
                    DropdownMenuItem(
                        text = { Text("📂 Open Project...") },
                        onClick = {
                            onNavigate(Screen.OPEN_PROJECT)
                            showFileMenu = false
                        }
                    )
                    HorizontalDivider()
                    DropdownMenuItem(
                        text = { Text("🚪 Exit Wizard") },
                        onClick = {
                            onExit()
                            showFileMenu = false
                        }
                    )
                }
            }

            Box {
                TextButton(onClick = { showHelpMenu = true }) {
                    Text("Help", color = MaterialTheme.colorScheme.onSurfaceVariant)
                }
                DropdownMenu(
                    expanded = showHelpMenu,
                    onDismissRequest = { showHelpMenu = false }
                ) {
                    DropdownMenuItem(
                        text = { Text("ℹ About Project Wizard") },
                        onClick = {
                            onNavigate(Screen.ABOUT)
                            showHelpMenu = false
                        }
                    )
                }
            }
        }

        // Quick action toolbar icons
        Row(
            horizontalArrangement = Arrangement.spacedBy(16.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            IconButton(onClick = { onNavigate(Screen.NEW_PROJECT) }) {
                Icon(
                    imageVector = Icons.Default.Add,
                    contentDescription = "New Project Quick Icon",
                    tint = MaterialTheme.colorScheme.primary
                )
            }
            IconButton(onClick = { onNavigate(Screen.OPEN_PROJECT) }) {
                Icon(
                    imageVector = Icons.Default.FolderOpen,
                    contentDescription = "Open Project Quick Icon",
                    tint = MaterialTheme.colorScheme.primary
                )
            }
            IconButton(onClick = { onNavigate(Screen.SETTINGS) }) {
                Icon(
                    imageVector = Icons.Default.Settings,
                    contentDescription = "Settings Quick Icon",
                    tint = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }
        }
    }
}

// Bottom status bar displaying system states
@Composable
fun BottomStatusBar(
    currentScreen: Screen,
    activeProject: GeneratedProject?
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .background(MaterialTheme.colorScheme.surfaceVariant)
            .padding(horizontal = 16.dp, vertical = 6.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween
    ) {
        Row(
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            Box(
                modifier = Modifier
                    .size(8.dp)
                    .clip(RoundedCornerShape(4.dp))
                    .background(Color(0xFF4CAF50)) // Green ready circle
            )
            Text(
                text = if (currentScreen == Screen.WORKSPACE && activeProject != null) {
                    "Workspace: ${activeProject.name}"
                } else {
                    "Ready"
                },
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }

        Text(
            text = "SDK 35 | JDT Engine | v1.0.0",
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )
    }
}

// --- 1. DASHBOARD SCREEN ---
@Composable
fun DashboardScreen(
    onNewProject: () -> Unit,
    onOpenProject: () -> Unit
) {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(24.dp)
            .verticalScroll(rememberScrollState()),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Text(
            text = "🧙‍♂️ Project Wizard",
            fontSize = 32.sp,
            fontWeight = FontWeight.Bold,
            color = MaterialTheme.colorScheme.primary,
            modifier = Modifier.padding(bottom = 8.dp)
        )
        Text(
            text = "Create amazing desktop, backend, and console projects with ease",
            fontSize = 16.sp,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
            modifier = Modifier.padding(bottom = 32.dp),
            style = MaterialTheme.typography.bodyLarge
        )

        Row(
            modifier = Modifier
                .fillMaxWidth()
                .widthIn(max = 600.dp),
            horizontalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            Card(
                onClick = onNewProject,
                modifier = Modifier
                    .weight(1f)
                    .height(180.dp)
                    .testTag("dashboard_new_project_card"),
                colors = CardDefaults.cardColors(
                    containerColor = MaterialTheme.colorScheme.surfaceVariant
                ),
                elevation = CardDefaults.cardElevation(4.dp)
            ) {
                Column(
                    modifier = Modifier
                        .fillMaxSize()
                        .padding(16.dp),
                    verticalArrangement = Arrangement.SpaceBetween
                ) {
                    Icon(
                        imageVector = Icons.Default.CreateNewFolder,
                        contentDescription = null,
                        modifier = Modifier.size(40.dp),
                        tint = MaterialTheme.colorScheme.primary
                    )
                    Column {
                        Text(
                            text = "New Project",
                            fontWeight = FontWeight.Bold,
                            fontSize = 18.sp,
                            color = MaterialTheme.colorScheme.onSurface
                        )
                        Text(
                            text = "Generate a new codebase",
                            fontSize = 12.sp,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                }
            }

            Card(
                onClick = onOpenProject,
                modifier = Modifier
                    .weight(1f)
                    .height(180.dp)
                    .testTag("dashboard_open_project_card"),
                colors = CardDefaults.cardColors(
                    containerColor = MaterialTheme.colorScheme.surfaceVariant
                ),
                elevation = CardDefaults.cardElevation(4.dp)
            ) {
                Column(
                    modifier = Modifier
                        .fillMaxSize()
                        .padding(16.dp),
                    verticalArrangement = Arrangement.SpaceBetween
                ) {
                    Icon(
                        imageVector = Icons.Default.FolderOpen,
                        contentDescription = null,
                        modifier = Modifier.size(40.dp),
                        tint = MaterialTheme.colorScheme.secondary
                    )
                    Column {
                        Text(
                            text = "Open Project",
                            fontWeight = FontWeight.Bold,
                            fontSize = 18.sp,
                            color = MaterialTheme.colorScheme.onSurface
                        )
                        Text(
                            text = "Open and edit existing projects",
                            fontSize = 12.sp,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                }
            }
        }
    }
}

// --- 2. NEW PROJECT WIZARD SCREEN ---
@Composable
fun NewProjectWizardScreen(
    initialTemplate: ProjectTemplate?,
    onCancel: () -> Unit,
    onFinish: (String, String, String, String, String) -> Unit
) {
    var step by remember { mutableIntStateOf(0) }
    val stepsList = listOf("Project", "Language", "Build Tool", "Summary")

    // Form states
    var projectName by remember { mutableStateOf(initialTemplate?.name?.replace(" ", "") ?: "MyProject") }
    var group by remember { mutableStateOf("com.example") }
    var artifact by remember { mutableStateOf(initialTemplate?.id ?: "sampleapp") }
    var language by remember { mutableStateOf(if (initialTemplate?.category == "Kotlin") "Kotlin" else "Java") }
    var buildTool by remember { mutableStateOf("Gradle") }

    Row(modifier = Modifier.fillMaxSize()) {
        // Steps indicator left pane (IDE style wizard side bar)
        Column(
            modifier = Modifier
                .width(180.dp)
                .fillMaxHeight()
                .background(MaterialTheme.colorScheme.surface)
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            Text(
                text = "Wizard Steps",
                fontWeight = FontWeight.Bold,
                fontSize = 14.sp,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                modifier = Modifier.padding(bottom = 8.dp)
            )
            stepsList.forEachIndexed { index: Int, label: String ->
                val isActive = step == index
                val isCompleted = step > index
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Box(
                        modifier = Modifier
                            .size(24.dp)
                            .clip(RoundedCornerShape(12.dp))
                            .background(
                                when {
                                    isActive -> MaterialTheme.colorScheme.primary
                                    isCompleted -> Color(0xFF4CAF50)
                                    else -> MaterialTheme.colorScheme.surfaceVariant
                                }
                            ),
                        contentAlignment = Alignment.Center
                    ) {
                        if (isCompleted) {
                            Icon(
                                imageVector = Icons.Default.Check,
                                contentDescription = null,
                                modifier = Modifier.size(12.dp),
                                tint = Color.White
                            )
                        } else {
                            Text(
                                text = (index + 1).toString(),
                                fontSize = 11.sp,
                                fontWeight = FontWeight.Bold,
                                color = if (isActive) MaterialTheme.colorScheme.onPrimary else MaterialTheme.colorScheme.onSurfaceVariant
                            )
                        }
                    }
                    Text(
                        text = label,
                        fontSize = 14.sp,
                        fontWeight = if (isActive) FontWeight.SemiBold else FontWeight.Normal,
                        color = if (isActive) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
            }
        }

        VerticalDivider(color = MaterialTheme.colorScheme.outline, modifier = Modifier.width(1.dp).fillMaxHeight())

        // Form fields center pane
        Column(
            modifier = Modifier
                .weight(1f)
                .fillMaxHeight()
                .padding(24.dp)
        ) {
            Text(
                text = "Create New Project",
                fontSize = 24.sp,
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.onSurface,
                modifier = Modifier.padding(bottom = 16.dp)
            )

            Box(modifier = Modifier.weight(1f)) {
                when (step) {
                    0 -> Column(verticalArrangement = Arrangement.spacedBy(16.dp)) {
                        Text("Configure your project basic identification properties.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                        OutlinedTextField(
                            value = projectName,
                            onValueChange = { projectName = it },
                            label = { Text("Project Name") },
                            modifier = Modifier
                                .fillMaxWidth()
                                .testTag("wizard_proj_name"),
                            singleLine = true
                        )
                        OutlinedTextField(
                            value = group,
                            onValueChange = { group = it },
                            label = { Text("Group ID") },
                            modifier = Modifier.fillMaxWidth(),
                            singleLine = true
                        )
                        OutlinedTextField(
                            value = artifact,
                            onValueChange = { artifact = it },
                            label = { Text("Artifact ID") },
                            modifier = Modifier.fillMaxWidth(),
                            singleLine = true
                        )
                    }
                    1 -> Column(verticalArrangement = Arrangement.spacedBy(16.dp)) {
                        Text("Select your primary programming language.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                        Row(horizontalArrangement = Arrangement.spacedBy(16.dp)) {
                            Card(
                                onClick = { language = "Java" },
                                modifier = Modifier
                                    .weight(1f)
                                    .height(100.dp),
                                border = BorderStroke(
                                    2.dp,
                                    if (language == "Java") MaterialTheme.colorScheme.primary else Color.Transparent
                                )
                            ) {
                                Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                                    Text("☕ Java", fontSize = 18.sp, fontWeight = FontWeight.Bold)
                                }
                            }
                            Card(
                                onClick = { language = "Kotlin" },
                                modifier = Modifier
                                    .weight(1f)
                                    .height(100.dp),
                                border = BorderStroke(
                                    2.dp,
                                    if (language == "Kotlin") MaterialTheme.colorScheme.primary else Color.Transparent
                                )
                            ) {
                                Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                                    Text("🎯 Kotlin", fontSize = 18.sp, fontWeight = FontWeight.Bold)
                                }
                            }
                        }
                    }
                    2 -> Column(verticalArrangement = Arrangement.spacedBy(16.dp)) {
                        Text("Choose the dependency management and build orchestrator.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                        Row(horizontalArrangement = Arrangement.spacedBy(16.dp)) {
                            Card(
                                onClick = { buildTool = "Gradle" },
                                modifier = Modifier
                                    .weight(1f)
                                    .height(100.dp),
                                border = BorderStroke(
                                    2.dp,
                                    if (buildTool == "Gradle") MaterialTheme.colorScheme.primary else Color.Transparent
                                )
                            ) {
                                Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                                    Text("🐘 Gradle", fontSize = 18.sp, fontWeight = FontWeight.Bold)
                                }
                            }
                            Card(
                                onClick = { buildTool = "Maven" },
                                modifier = Modifier
                                    .weight(1f)
                                    .height(100.dp),
                                border = BorderStroke(
                                    2.dp,
                                    if (buildTool == "Maven") MaterialTheme.colorScheme.primary else Color.Transparent
                                )
                            ) {
                                Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                                    Text("📦 Maven", fontSize = 18.sp, fontWeight = FontWeight.Bold)
                                }
                            }
                        }
                    }
                    3 -> Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                        Text("Review project generation configuration summary.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                        Card(
                            modifier = Modifier.fillMaxWidth(),
                            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
                        ) {
                            Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                                Text("📁 Project Name: $projectName", fontWeight = FontWeight.SemiBold)
                                Text("🆔 Group ID: $group")
                                Text("📦 Artifact ID: $artifact")
                                Text("☕ Language: $language")
                                Text("⚙ Build Tool: $buildTool")
                                Text("📍 Location: Virtual Workspace")
                            }
                        }
                    }
                }
            }

            // Navigation Wizard buttons
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Button(
                    onClick = onCancel,
                    colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.surfaceVariant, contentColor = MaterialTheme.colorScheme.onSurface)
                ) {
                    Text("Cancel")
                }

                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    if (step > 0) {
                        Button(onClick = { step-- }) {
                            Icon(Icons.AutoMirrored.Filled.ArrowBack, null, modifier = Modifier.size(16.dp))
                            Spacer(Modifier.width(4.dp))
                            Text("Back")
                        }
                    }
                    if (step < stepsList.size - 1) {
                        Button(
                            onClick = { step++ },
                            modifier = Modifier.testTag("wizard_next_btn")
                        ) {
                            Text("Next")
                            Spacer(Modifier.width(4.dp))
                            Icon(Icons.AutoMirrored.Filled.ArrowForward, null, modifier = Modifier.size(16.dp))
                        }
                    } else {
                        Button(
                            onClick = { onFinish(projectName, group, artifact, language, buildTool) },
                            colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF4CAF50)),
                            modifier = Modifier.testTag("wizard_finish_btn")
                        ) {
                            Icon(Icons.Default.Done, null)
                            Spacer(Modifier.width(4.dp))
                            Text("Finish")
                        }
                    }
                }
            }
        }
    }
}

// --- 3. OPEN PROJECT / WORKSPACE CHOOSER ---
@Composable
fun OpenProjectScreen(
    projects: List<GeneratedProject>,
    onProjectSelected: (GeneratedProject) -> Unit,
    onDeleteProject: (GeneratedProject) -> Unit
) {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(24.dp)
    ) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Column {
                Text(
                    text = "Open Project Folder",
                    fontSize = 24.sp,
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.onSurface
                )
                Text(
                    text = "Choose from virtual storage workspace sandbox directories.",
                    fontSize = 14.sp,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }
        }

        Spacer(modifier = Modifier.height(20.dp))

        if (projects.isEmpty()) {
            Box(modifier = Modifier.weight(1f).fillMaxWidth(), contentAlignment = Alignment.Center) {
                Text("No projects found. Generate one in the New Project Wizard!", color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
        } else {
            LazyColumn(
                modifier = Modifier.weight(1f),
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                items(projects) { project: GeneratedProject ->
                    var showConfirmDelete by remember { mutableStateOf(false) }

                    Card(
                        onClick = { onProjectSelected(project) },
                        modifier = Modifier
                            .fillMaxWidth()
                            .testTag("project_item_" + project.name.lowercase(Locale.ROOT)),
                        colors = CardDefaults.cardColors(
                            containerColor = MaterialTheme.colorScheme.surfaceVariant
                        )
                    ) {
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(16.dp),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Row(
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.spacedBy(16.dp)
                            ) {
                                Text(
                                    text = if (project.language == "Kotlin") "🎯" else "☕",
                                    fontSize = 28.sp
                                )
                                Column {
                                    Text(
                                        text = project.name,
                                        fontWeight = FontWeight.Bold,
                                        fontSize = 16.sp
                                    )
                                    Text(
                                        text = project.path,
                                        fontSize = 12.sp,
                                        color = MaterialTheme.colorScheme.onSurfaceVariant
                                    )
                                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                                        SuggestionChip(onClick = {}, label = { Text(project.language) })
                                        SuggestionChip(onClick = {}, label = { Text(project.buildTool) })
                                    }
                                }
                            }

                            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                                IconButton(onClick = { onProjectSelected(project) }) {
                                    Icon(Icons.Default.PlayArrow, "Open Project", tint = MaterialTheme.colorScheme.primary)
                                }
                                IconButton(onClick = { showConfirmDelete = true }) {
                                    Icon(Icons.Default.Delete, "Delete", tint = Color(0xFFE53935))
                                }
                            }
                        }
                    }

                    if (showConfirmDelete) {
                        AlertDialog(
                            onDismissRequest = { showConfirmDelete = false },
                            title = { Text("Delete Project") },
                            text = { Text("Are you sure you want to delete '${project.name}'? This cannot be undone.") },
                            confirmButton = {
                                TextButton(onClick = {
                                    onDeleteProject(project)
                                    showConfirmDelete = false
                                }) {
                                    Text("Delete", color = Color(0xFFE53935))
                                }
                            },
                            dismissButton = {
                                TextButton(onClick = { showConfirmDelete = false }) {
                                    Text("Cancel")
                                }
                            }
                        )
                    }
                }
            }
        }
    }
}

// --- 4. PROJECT WORKSPACE TWO-PANE INTEGRATION ---
@Composable
fun ProjectWorkspaceScreen(
    project: GeneratedProject,
    persistenceService: PersistenceService,
    onCloseWorkspace: () -> Unit
) {
    // Keep track of opened file and expanded directories
    var openFile by remember { mutableStateOf<File?>(null) }
    var fileContent by remember { mutableStateOf("") }
    var editorModified by remember { mutableStateOf(false) }

    // Collage state for collapsed directories in PackageExplorer
    val expandedPaths = remember { mutableStateListOf<String>() }

    // Refresh tree trigger
    var treeRefreshKey by remember { mutableIntStateOf(0) }

    val context = LocalContext.current
    val projectDir = File(project.path)

    // Automatically load the project README.md on open or restore last file
    LaunchedEffect(project.path) {
        val openFiles: List<String> = persistenceService.getOpenFiles()
        val lastFile = if (openFiles.isNotEmpty()) File(openFiles[0]) else File(projectDir, "README.md")
        
        if (lastFile.exists() && lastFile.isFile) {
            openFile = lastFile
            fileContent = lastFile.readText()
            editorModified = false
        }
    }

    // Save open file to persistence
    LaunchedEffect(openFile) {
        val currentFile = openFile
        if (currentFile != null) {
            persistenceService.saveOpenFiles(listOf(currentFile.absolutePath))
        }
    }

    Row(modifier = Modifier.fillMaxSize()) {
        // Left column: Collapsible File Explorer tree (PackageExplorer)
        Column(
            modifier = Modifier
                .width(260.dp)
                .fillMaxHeight()
                .background(MaterialTheme.colorScheme.surface)
                .border(1.dp, MaterialTheme.colorScheme.outline, RoundedCornerShape(0.dp))
        ) {
            // Explorer Title
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(12.dp),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                    Icon(Icons.Default.Folder, null, tint = MaterialTheme.colorScheme.primary, modifier = Modifier.size(16.dp))
                    Text("Package Explorer", fontWeight = FontWeight.Bold, fontSize = 14.sp)
                }
                IconButton(onClick = onCloseWorkspace) {
                    Icon(Icons.Default.Close, "Close project", modifier = Modifier.size(16.dp))
                }
            }

            HorizontalDivider(color = MaterialTheme.colorScheme.outline)

            // Real recursive file tree structure in LazyColumn
            key(treeRefreshKey) {
                LazyColumn(
                    modifier = Modifier
                        .fillMaxSize()
                        .padding(horizontal = 4.dp, vertical = 8.dp)
                ) {
                    item {
                        // Project root row
                        FileTreeRow(
                            file = projectDir,
                            indentation = 0,
                            isExpanded = expandedPaths.contains(projectDir.absolutePath),
                            onRowClicked = {
                                if (expandedPaths.contains(projectDir.absolutePath)) {
                                    expandedPaths.remove(projectDir.absolutePath)
                                } else {
                                    expandedPaths.add(projectDir.absolutePath)
                                }
                            }
                        )
                    }

                    // Children expansion
                    if (expandedPaths.contains(projectDir.absolutePath)) {
                        val itemsList = mutableListOf<Pair<File, Int>>()
                        val expandedSet = HashSet<String>()
                        for (path in expandedPaths) expandedSet.add(path)
                        buildFileTreeList(projectDir, 1, expandedSet, itemsList)

                        items(itemsList) { pair: Pair<File, Int> ->
                            val file = pair.first
                            val indent = pair.second
                            FileTreeRow(
                                file = file,
                                indentation = indent,
                                isExpanded = expandedPaths.contains(file.absolutePath),
                                onRowClicked = {
                                    if (file.isDirectory) {
                                        if (expandedPaths.contains(file.absolutePath)) {
                                            expandedPaths.remove(file.absolutePath)
                                        } else {
                                            expandedPaths.add(file.absolutePath)
                                        }
                                    } else {
                                        // Open text file
                                        try {
                                            openFile = file
                                            fileContent = file.readText()
                                            editorModified = false
                                        } catch (e: Exception) {
                                            Toast.makeText(context, "Cannot open: ${e.message}", Toast.LENGTH_SHORT).show()
                                        }
                                    }
                                }
                            )
                        }
                    }
                }
            }
        }

        VerticalDivider(color = MaterialTheme.colorScheme.outline, modifier = Modifier.width(1.dp).fillMaxHeight())

        // Right column: Code Editor (EditorPane)
        Column(
            modifier = Modifier
                .weight(1f)
                .fillMaxHeight()
                .background(MaterialTheme.colorScheme.background)
        ) {
            val activeFile = openFile
            if (activeFile != null) {
                // Editor File toolbar header
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .background(MaterialTheme.colorScheme.surfaceVariant)
                        .padding(horizontal = 16.dp, vertical = 8.dp),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Column {
                        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                            Text(
                                text = activeFile.name,
                                fontWeight = FontWeight.Bold,
                                color = MaterialTheme.colorScheme.onSurface
                            )
                            if (editorModified) {
                                Box(
                                    modifier = Modifier
                                        .size(6.dp)
                                        .clip(RoundedCornerShape(3.dp))
                                        .background(MaterialTheme.colorScheme.primary)
                                )
                            }
                        }
                        Text(
                            text = activeFile.parent ?: "",
                            fontSize = 11.sp,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }

                    // Save file button
                    Button(
                        onClick = {
                            try {
                                activeFile.writeText(fileContent)
                                editorModified = false
                                treeRefreshKey++
                                Toast.makeText(context, "File saved successfully!", Toast.LENGTH_SHORT).show()
                            } catch (e: Exception) {
                                Toast.makeText(context, "Save error: ${e.message}", Toast.LENGTH_SHORT).show()
                            }
                        },
                        colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.primary),
                        shape = RoundedCornerShape(6.dp),
                        contentPadding = PaddingValues(horizontal = 12.dp, vertical = 4.dp),
                        modifier = Modifier.testTag("editor_save_btn")
                    ) {
                        Icon(Icons.Default.Save, null, modifier = Modifier.size(16.dp))
                        Spacer(modifier = Modifier.width(4.dp))
                        Text("Save")
                    }
                }

                HorizontalDivider(color = MaterialTheme.colorScheme.outline)

                // Editable Code Canvas with Line Numbers and Syntax Highlighting
                Row(modifier = Modifier.fillMaxSize()) {
                    // Line numbers column
                    val lineCount = fileContent.split("\n").size
                    Column(
                        modifier = Modifier
                            .background(MaterialTheme.colorScheme.surface)
                            .padding(horizontal = 8.dp, vertical = 16.dp)
                            .fillMaxHeight(),
                        horizontalAlignment = Alignment.End
                    ) {
                        for (i in 1..lineCount) {
                            Text(
                                text = i.toString(),
                                style = MaterialTheme.typography.bodySmall.copy(
                                    fontFamily = FontFamily.Monospace,
                                    color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.5f)
                                )
                            )
                        }
                    }

                    VerticalDivider(color = MaterialTheme.colorScheme.outline, modifier = Modifier.width(1.dp).fillMaxHeight())

                    // Raw text editor with formatted syntax highlighting overlay
                    Box(
                        modifier = Modifier
                            .weight(1f)
                            .fillMaxHeight()
                            .verticalScroll(rememberScrollState())
                            .horizontalScroll(rememberScrollState())
                            .padding(16.dp)
                    ) {
                        // Highlighting parser
                        val isDark = ThemeManager.currentTheme == ThemeType.PRIMER_DARK || 
                                     ThemeManager.currentTheme == ThemeType.DRACULA ||
                                     ThemeManager.currentTheme == ThemeType.NORD_DARK ||
                                     ThemeManager.currentTheme == ThemeType.CUPERTINO_DARK
                        val highlightedText = remember(fileContent, activeFile.name, isDark) {
                            SyntaxHighlighter.highlight(fileContent, activeFile.name, isDark)
                        }

                        // BasicTextField with VisualTransformation is an option, but for direct robust display,
                        // we can overlay a custom styled TextField or direct Editable text box
                        BasicTextField(
                            value = fileContent,
                            onValueChange = {
                                fileContent = it
                                editorModified = true
                            },
                            textStyle = MaterialTheme.typography.bodyMedium.copy(
                                fontFamily = FontFamily.Monospace,
                                color = MaterialTheme.colorScheme.onBackground
                            ),
                            modifier = Modifier
                                .fillMaxSize()
                                .testTag("code_editor_field"),
                            // Here we use Custom Visual Transformation to apply styling
                            visualTransformation = VisualTransformation { text ->
                                TransformedText(highlightedText, OffsetMapping.Identity)
                            }
                        )
                    }
                }
            } else {
                Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                    Text("Select a file from the explorer to open in the code editor.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                }
            }
        }
    }
}

// Utility function to recursive list directories for collapse explorer
fun buildFileTreeList(dir: File, indent: Int, expandedPaths: Set<String>, list: MutableList<Pair<File, Int>>) {
    val files = dir.listFiles() ?: return
    // Sort directories first, then files
    files.sortWith(compareBy({ !it.isDirectory }, { it.name.lowercase() }))

    for (file in files) {
        list.add(Pair(file, indent))
        if (file.isDirectory && expandedPaths.contains(file.absolutePath)) {
            buildFileTreeList(file, indent + 1, expandedPaths, list)
        }
    }
}


@Composable
fun FileTreeRow(
    file: File,
    indentation: Int,
    isExpanded: Boolean,
    onRowClicked: () -> Unit
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clickable(onClick = onRowClicked)
            .padding(vertical = 4.dp, horizontal = 4.dp)
            .padding(start = (indentation * 16).dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        // Toggle expansion icon for folder
        if (file.isDirectory) {
            Icon(
                imageVector = if (isExpanded) Icons.Default.ArrowDropDown else Icons.AutoMirrored.Filled.ArrowForward,
                contentDescription = null,
                modifier = Modifier.size(16.dp),
                tint = MaterialTheme.colorScheme.onSurfaceVariant
            )
            Icon(
                imageVector = Icons.Default.Folder,
                contentDescription = null,
                modifier = Modifier.size(18.dp),
                tint = Color(0xFFFFB300) // Beautiful Folder gold
            )
        } else {
            Spacer(modifier = Modifier.width(16.dp))
            val ext = file.name.substringAfterLast(".", "").lowercase()
            val fileIcon = when (ext) {
                "java" -> "☕"
                "kt", "kts" -> "🎯"
                "xml", "html" -> "🌐"
                "gradle" -> "🐘"
                "md" -> "📝"
                "json" -> "⚙️"
                else -> "📄"
            }
            Text(fileIcon, fontSize = 14.sp)
        }

        Spacer(modifier = Modifier.width(6.dp))

        Text(
            text = file.name,
            fontSize = 13.sp,
            fontFamily = if (file.isDirectory) FontFamily.Default else FontFamily.Monospace,
            fontWeight = if (file.isDirectory) FontWeight.SemiBold else FontWeight.Normal,
            color = MaterialTheme.colorScheme.onSurface
        )
    }
}

// --- 5. TEMPLATES CATALOG SCREEN ---
@Composable
fun TemplatesScreen(
    onSelectTemplate: (ProjectTemplate) -> Unit
) {
    var searchQuery by remember { mutableStateOf("") }
    var selectedCategory by remember { mutableStateOf("All") }
    var selectedTemplate by remember { mutableStateOf(ALL_TEMPLATES.first()) }

    val filteredTemplates = ALL_TEMPLATES.filter {
        (selectedCategory == "All" || it.category == selectedCategory) &&
                (it.name.contains(searchQuery, ignoreCase = true) || it.description.contains(searchQuery, ignoreCase = true))
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(20.dp)
    ) {
        Text(
            text = "Choose Project Type",
            fontSize = 24.sp,
            fontWeight = FontWeight.Bold,
            modifier = Modifier.padding(bottom = 12.dp)
        )

        // Toolbar: search & filtering row
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(12.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            OutlinedTextField(
                value = searchQuery,
                onValueChange = { searchQuery = it },
                placeholder = { Text("Search templates...") },
                modifier = Modifier.weight(1f),
                singleLine = true,
                leadingIcon = { Icon(Icons.Default.Search, null) }
            )

            val categories = listOf("All", "Java", "Desktop", "Spring", "Library")
            var dropdownExpanded by remember { mutableStateOf(false) }

            Box {
                Button(onClick = { dropdownExpanded = true }) {
                    Text("Category: $selectedCategory")
                }
                DropdownMenu(expanded = dropdownExpanded, onDismissRequest = { dropdownExpanded = false }) {
                    categories.forEach { cat ->
                        DropdownMenuItem(
                            text = { Text(cat) },
                            onClick = {
                                selectedCategory = cat
                                dropdownExpanded = false
                            }
                        )
                    }
                }
            }
        }

        Spacer(modifier = Modifier.height(16.dp))

        // Split view list & detail pane on larger screens
        Row(
            modifier = Modifier.fillMaxWidth().weight(1f),
            horizontalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // Left list of templates
            LazyColumn(
                modifier = Modifier.weight(1.5f),
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                items(filteredTemplates) { template: ProjectTemplate ->
                    val isSelected = selectedTemplate.id == template.id
                    Card(
                        onClick = { selectedTemplate = template },
                        modifier = Modifier
                            .fillMaxWidth()
                            .testTag("template_card_${template.id}"),
                        border = BorderStroke(
                            2.dp,
                            if (isSelected) MaterialTheme.colorScheme.primary else Color.Transparent
                        )
                    ) {
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(12.dp),
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(12.dp)
                        ) {
                            Text(template.icon, fontSize = 28.sp)
                            Column {
                                Text(template.name, fontWeight = FontWeight.Bold, fontSize = 16.sp)
                                Text(template.description, fontSize = 12.sp, color = MaterialTheme.colorScheme.onSurfaceVariant)
                            }
                        }
                    }
                }
            }

            VerticalDivider(color = MaterialTheme.colorScheme.outline, modifier = Modifier.width(1.dp).fillMaxHeight())

            // Right Detail Card Pane
            Card(
                modifier = Modifier
                    .weight(1f)
                    .fillMaxHeight(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
            ) {
                Column(
                    modifier = Modifier
                        .fillMaxSize()
                        .padding(16.dp),
                    verticalArrangement = Arrangement.SpaceBetween
                ) {
                    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                        Text(
                            text = "Template Details",
                            fontWeight = FontWeight.Bold,
                            fontSize = 12.sp,
                            color = MaterialTheme.colorScheme.primary
                        )
                        Text(
                            text = "${selectedTemplate.icon} ${selectedTemplate.name}",
                            fontWeight = FontWeight.Bold,
                            fontSize = 20.sp
                        )
                        Text(
                            text = selectedTemplate.description,
                            fontSize = 14.sp,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                        HorizontalDivider(color = MaterialTheme.colorScheme.outline)
                        Text(
                            text = "Tech Stack:",
                            fontWeight = FontWeight.Bold,
                            fontSize = 13.sp
                        )
                        Text(
                            text = selectedTemplate.techStack,
                            fontSize = 13.sp,
                            fontFamily = FontFamily.Monospace,
                            color = MaterialTheme.colorScheme.secondary
                        )
                    }

                    Button(
                        onClick = { onSelectTemplate(selectedTemplate) },
                        modifier = Modifier
                            .fillMaxWidth()
                            .testTag("create_proj_from_template_btn")
                    ) {
                        Text("Create Project")
                    }
                }
            }
        }
    }
}

// --- 6. GIT INTEGRATIONS SCREEN ---
@Composable
fun GitScreen(activeProject: GeneratedProject?) {
    val gitService = remember(activeProject) { 
        if (activeProject != null) GitService(File(activeProject.path)) else null
    }
    
    var gitStatusLog by remember { 
        mutableStateOf(gitService?.repositoryInfo ?: "Open a project to see Git status")
    }
    var commitMessage by remember { mutableStateOf("") }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(24.dp)
            .verticalScroll(rememberScrollState()),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        Text("🌿 Git Version Control Integration", fontSize = 24.sp, fontWeight = FontWeight.Bold)

        if (activeProject == null) {
            Card(modifier = Modifier.fillMaxWidth()) {
                Text(
                    "Please open a project to manage Git repository.",
                    modifier = Modifier.padding(16.dp),
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }
        } else {
            Card(modifier = Modifier.fillMaxWidth()) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    Text("Git Operations: ${activeProject.name}", fontWeight = FontWeight.SemiBold, color = MaterialTheme.colorScheme.primary)
                    
                    val isGit = gitService?.isGitRepository ?: false
                    val branch = gitService?.currentBranch ?: "unknown"
                    val remote = gitService?.remoteUrl ?: "None"
                    
                    if (isGit) {
                        Text("Current Branch: $branch", style = MaterialTheme.typography.bodyMedium)
                        Text("Remote: $remote", style = MaterialTheme.typography.bodySmall)
                    }

                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp), modifier = Modifier.fillMaxWidth()) {
                        Button(
                            onClick = { 
                                // Simulated Init
                                gitStatusLog = "Initialized empty Git repository in ${activeProject.path}/.git/" 
                            },
                            enabled = gitService?.isGitRepository != true
                        ) {
                            Text("Git Init")
                        }
                        Button(
                            onClick = {
                                gitStatusLog = gitService?.repositoryInfo ?: "Error reading Git status"
                            },
                            enabled = gitService?.isGitRepository == true
                        ) {
                            Text("Refresh Status")
                        }
                    }

                    OutlinedTextField(
                        value = commitMessage,
                        onValueChange = { commitMessage = it },
                        label = { Text("Commit Message") },
                        modifier = Modifier.fillMaxWidth(),
                        enabled = gitService?.isGitRepository == true
                    )

                    Button(
                        onClick = {
                            if (commitMessage.isBlank()) {
                                gitStatusLog = "Error: Commit message cannot be empty!"
                            } else {
                                gitStatusLog = "[main 4c3df91] $commitMessage\n 1 file changed, 4 insertions(+), 1 deletion(-)"
                                commitMessage = ""
                            }
                        },
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF4CAF50)),
                        enabled = gitService?.isGitRepository == true
                    ) {
                        Text("Git Commit")
                    }
                }
            }
        }

        Text("Console Log Output", fontWeight = FontWeight.Bold, fontSize = 14.sp)
        Card(
            modifier = Modifier
                .fillMaxWidth()
                .height(180.dp),
            colors = CardDefaults.cardColors(containerColor = Color.Black)
        ) {
            Box(
                modifier = Modifier
                    .fillMaxSize()
                    .verticalScroll(rememberScrollState())
                    .padding(12.dp)
            ) {
                Text(
                    text = gitStatusLog,
                    fontFamily = FontFamily.Monospace,
                    fontSize = 12.sp,
                    color = Color(0xFF4CAF50) // Green console text
                )
            }
        }
    }
}

// --- 7. GITHUB VIEWS SCREEN ---
@Composable
fun GitHubScreen() {
    var loggedIn by remember { mutableStateOf(false) }
    var reposList by remember { mutableStateOf(listOf("My_Console_App", "My_Spring_API")) }
    var newRepoName by remember { mutableStateOf("") }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(24.dp)
            .verticalScroll(rememberScrollState()),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        Text("🐙 GitHub Core Cloud Integration", fontSize = 24.sp, fontWeight = FontWeight.Bold)

        if (!loggedIn) {
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
            ) {
                Column(
                    modifier = Modifier.padding(24.dp),
                    horizontalAlignment = Alignment.CenterHorizontally,
                    verticalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    Text("Sign in to your GitHub developer account", fontWeight = FontWeight.SemiBold)
                    Button(onClick = { loggedIn = true }) {
                        Text("Login with GitHub OAuth")
                    }
                }
            }
        } else {
            Card(modifier = Modifier.fillMaxWidth()) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text("Authenticated as marcel1237", fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.primary)
                        TextButton(onClick = { loggedIn = false }) {
                            Text("Logout")
                        }
                    }

                    HorizontalDivider()

                    Text("Create New Remote Repository", fontWeight = FontWeight.SemiBold)
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        OutlinedTextField(
                            value = newRepoName,
                            onValueChange = { newRepoName = it },
                            placeholder = { Text("repo-name") },
                            modifier = Modifier.weight(1f),
                            singleLine = true
                        )
                        Button(onClick = {
                            if (newRepoName.isNotBlank()) {
                                reposList += newRepoName
                                newRepoName = ""
                            }
                        }) {
                            Text("Create")
                        }
                    }

                    Spacer(modifier = Modifier.height(8.dp))

                    Text("Your GitHub Repositories", fontWeight = FontWeight.Bold)
                    reposList.forEach { repo: String ->
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .background(MaterialTheme.colorScheme.surfaceVariant)
                                .padding(10.dp),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text("📦 github.com/marcel1237/$repo", fontSize = 13.sp, fontFamily = FontFamily.Monospace)
                            SuggestionChip(onClick = {}, label = { Text("Public") })
                        }
                    }
                }
            }
        }
    }
}

// --- 8. SETTINGS SCREEN (THEMING CONTROL) ---
@Composable
fun SettingsScreen(persistenceService: PersistenceService) {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(24.dp)
            .verticalScroll(rememberScrollState()),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        Text("⚙ Settings & Customization", fontSize = 24.sp, fontWeight = FontWeight.Bold)

        Card(modifier = Modifier.fillMaxWidth()) {
            Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                Text("App Color Theme Managers", fontWeight = FontWeight.SemiBold, color = MaterialTheme.colorScheme.primary)
                Text(
                    text = "Select from AtlantaFX equivalent custom dynamic color profiles.",
                    fontSize = 13.sp,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )

                val themes = listOf(
                    Pair("Primer Dark", ThemeType.PRIMER_DARK),
                    Pair("Dracula (Vampire Theme)", ThemeType.DRACULA),
                    Pair("Nord Dark Slate", ThemeType.NORD_DARK),
                    Pair("Cupertino Dark (Apple style)", ThemeType.CUPERTINO_DARK),
                    Pair("Primer Light", ThemeType.PRIMER_LIGHT),
                    Pair("Nord Light", ThemeType.NORD_LIGHT),
                    Pair("Cupertino Light", ThemeType.CUPERTINO_LIGHT)
                )

                themes.forEach { pair: Pair<String, ThemeType> ->
                    val label = pair.first
                    val type = pair.second
                    val isSelected = ThemeManager.currentTheme == type
                    Card(
                        onClick = { 
                            ThemeManager.currentTheme = type
                            persistenceService.saveTheme(type.name)
                        },
                        modifier = Modifier
                            .fillMaxWidth()
                            .testTag("theme_btn_" + type.name.lowercase(Locale.ROOT)),
                        colors = CardDefaults.cardColors(
                            containerColor = if (isSelected) MaterialTheme.colorScheme.primary.copy(alpha = 0.2f) else MaterialTheme.colorScheme.surfaceVariant
                        ),
                        border = BorderStroke(
                            1.dp,
                            if (isSelected) MaterialTheme.colorScheme.primary else Color.Transparent
                        )
                    ) {
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(14.dp),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(label, fontWeight = if (isSelected) FontWeight.Bold else FontWeight.Normal)
                            if (isSelected) {
                                Icon(Icons.Default.RadioButtonChecked, null, tint = MaterialTheme.colorScheme.primary)
                            } else {
                                Icon(Icons.Default.RadioButtonUnchecked, null, tint = MaterialTheme.colorScheme.onSurfaceVariant)
                            }
                        }
                    }
                }
            }
        }
    }
}

// --- 9. ABOUT SCREEN ---
@Composable
fun AboutScreen() {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(24.dp)
            .verticalScroll(rememberScrollState()),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        Text("ℹ About Project Wizard", fontSize = 24.sp, fontWeight = FontWeight.Bold, modifier = Modifier.padding(bottom = 12.dp))

        Card(
            modifier = Modifier.widthIn(max = 500.dp),
            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
        ) {
            Column(
                modifier = Modifier.padding(24.dp),
                verticalArrangement = Arrangement.spacedBy(12.dp),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Text("🧙‍♂️", fontSize = 64.sp)
                Text("Project Wizard", fontSize = 22.sp, fontWeight = FontWeight.Bold)
                Text("Version 1.0.0 (Android build)", fontSize = 14.sp, color = MaterialTheme.colorScheme.onSurfaceVariant)

                HorizontalDivider(color = MaterialTheme.colorScheme.outline)

                Text(
                    text = "A premium mobile-adaptive code wizard IDE, designed and ported from the Desktop ProjectWizard (developed in Java, JavaFX, and AtlantaFX). Easily orchestrate and scaffold full-stack backend, API services, libraries, and desktop templates directly from your mobile device.",
                    fontSize = 14.sp,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    modifier = Modifier.padding(vertical = 8.dp)
                )

                HorizontalDivider(color = MaterialTheme.colorScheme.outline)

                Text(
                    text = "License: EPL-2.0 AND MPL-2.0 AND AGPL-3.0-only",
                    fontSize = 12.sp,
                    fontWeight = FontWeight.SemiBold,
                    color = MaterialTheme.colorScheme.secondary
                )
            }
        }
    }
}
